### ISSUE TITLE
Further Viewport Calculation Issue

### ISSUE THREAD

**Issue by MAKOMO** [florianfesti/boxes#10]
For this issue I could not even find a good title as it is a bit weird.

Consider the following script that works as expected.
 
```
    def render(self):
        self.open()
        self.rectangularWall(10, 10)
        self.ctx.save()
        self.moveTo(5,5)
        self.ctx.rectangle(0, 0, 3, 3)
        self.ctx.fill()
        self.ctx.restore()
        self.close()
```

Now if you change the moveTo line to

`        self.moveTo(5.1,5)
`
or
`        self.moveTo(5,5.1)
`       

it still works. But changing it to

`        self.moveTo(5.1,5.1)
`       
fails.

While the SVG for the "working" variants generate a header like this

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="  20mm" height="  30mm" viewBox="0 970  20  30" version="1.1">
`

the header of this last failing one looks like this

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="  20mm" height="1010mm" viewBox="0 -10  20 1010 version="1.1">
`

**Comment by florianfesti** [comment]
Nice catch. There are actually two issues here. One hiding the other:
1) The svg parser does not match integer numbers without a fraction part
2) Paths without a transform attribute use a default transformation matrix - which I got wrong -  resulting in a y value of 0. This got hidden in the first case by not matching the points at all.

Both should be fixed now.

FYI: width=" 20mm" height=" 30mm" give the "physical size of the image (on the screen or on paper). viewBox="0 970 20 30" gives the local coordinates that should be mapped into this rectangle. x, y of the top left corner and then width and height relative to that. Note that local coordinates are without a unit and are only put into real world coordinates by this mapping.
