### ISSUE TITLE
TypeTray should have a top edge param

### ISSUE THREAD

**Issue by florianfesti** [florianfesti/boxes#107]
TypeTray only has two options for the top: Straight edge or closed top (using FingerJointEdge f).

This leaves at least the StackableEdge available for the bottom unmatched. One could argue the top edge should actually be freely selectable similar to the UniversalBox. Otoh this will make the UniversalBox redundant - which may be a good thing...

See also https://hackaday.io/project/10649-boxespy/discussion-118236

**Comment by Blancanegra** [comment]
Please keep UniversalBox, I found it very useful!

Maybe you should add inner divisions to UniversalBox, or lid support for TypeTray... crossing worlds! :)

**Comment by florianfesti** [comment]
I already added a top_edge param to the TypeTray  (https://github.com/florianfesti/boxes/commit/c0a782b745cb51909c6560fd9ec3a58ec88d200e). But the change is not in the web instance yet.
I will probably keep the UniversalBox to not confuse users too much, although the TypeTray can (almost) do everything the UniversalBox can plus the inner walls.

**Comment by florianfesti** [comment]
Ok, I was still missing the lids that belong to the top_edges. That's fixed now and already online. I will probably change the sides of the outside walls to the same f-F pattern as the universal box. But that's out of scope of this ticket. Closing as fixed.
