### ISSUE TITLE
Paint Storage - customizable grip hole

### ISSUE THREAD

**Issue by Blancanegra** [florianfesti/boxes#108]
The default grip hole width makes the walls too fragile. For small shelfs a hole in the wall to pass a hand finger would be enough to catch and carry it safely, keeping the wall strong.

Please consider to add "gripheight" and "gripwidth"parameters (like in type tray) to the generator.

**Comment by florianfesti** [comment]
I'd rather have a sane default.
https://github.com/florianfesti/boxes/blob/master/boxes/generators/paintbox.py#L79 creates the hole with h/4., 3./4.*x being the size. Can you try and then suggest some smaller values?

**Comment by Blancanegra** [comment]
I'm using the web generators on windows so I can't try the code but sure 3./4,*x is too wide.

In my case I have a lot of cans from common paints in the market: Tamiya, Americana, Vallejo... for my 3 mm thick shelfs a 16 mm diameter  hole seems to be enough to pass trough a finger and carry the stacked shelfs safely.

![paint-storage](https://user-images.githubusercontent.com/32768345/50913795-75948280-1435-11e9-8d87-47023626c469.jpg)
My shelfs, with no hole. 

Maybe a sane rule would consider ergonomic data (min & max values) like finger diameter and hand with to calculate proper holes. :)

**Comment by florianfesti** [comment]
Reduced width of the hole to half of the shelf. That should double the strength. I also increased the radius to max.

**Comment by florianfesti** [comment]
This ticket has a better photo than some Boxes.py generators...
