### ISSUE TITLE
Problem installing on Mac?

### ISSUE THREAD

**Issue by algernon71** [florianfesti/boxes#113]
When I try to run setup install on a Mac I get some errors.

I have tried to troubleshoot by installing cairo (with homebrew) etc but I am no python expert so unsure what the problem is?

Trying to install so I can use it in Inkscape but also play some with my rudimentary Pything knowledge ;-) 

Thanks for a great library btw!

Here is my error log:
> ./setup.py build
running build
running build_py
buildInkscapeExt()
Traceback (most recent call last):
  File "scripts/boxes2inkscape", line 29, in <module>
    import boxes.generators
ModuleNotFoundError: No module named 'boxes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/boxes2inkscape", line 32, in <module>
    import boxes.generators
  File "scripts/../boxes/__init__.py", line 23, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
error: [Errno 2] No such file or directory: 'inkscape': 'inkscape'

**Comment by florianfesti** [comment]
From the error message I'd guess that the Python binding for the cairo library is missing. The package may be named py2cairo. (python*-cairo or python*-cairocffi on Linux)

**Comment by florianfesti** [comment]
Unfortunately I don't have any experience on other operating systems than Linux.
If you run a Python shell can you do "import cairo"?

Another route could be running Boxes.py in a Docker container. It ships a Dockerfile at https://github.com/florianfesti/boxes/blob/master/scripts/Dockerfile But I have no idea how complicated that is on OSX.

**Comment by algernon71** [comment]
Ok, I could install a distro in virtualbox... tried quickly with Ubuntu (18.04) but it seems to be a mess to get pycairo installed without being experienced in python etc (?)

Any advice for the easiest setup to get this running?

All I would like to do is to be able to use the inkscape plugin or possibly some improvised scripts to create boxes outside the sample set etc...

**Comment by florianfesti** [comment]
Installing pycairo should be really easy with Ubuntu. Just use the package that comes with the distribution. I should be named python-cairo (according to Google). 
`sudo apt-get install python-cairo` should do the trick.

**Comment by muellermartin** [comment]
If you're using Homebrew to install dependencies, make sure to use the right pycairo Formula (e.g. py2cairo for Python 2 and py3cairo for Python 3). `brew install py3cairo` should install cairo and its dependencies.

Also the last line of you error output shows that Inkscape is not runnable from your shell:
```
error: [Errno 2] No such file or directory: 'inkscape': 'inkscape'
```
I suggest that you install Inkscape via Homebrew Cask, e.g. by running `brew cask install inkscape`. This way the command `inkscape` should be available in your shell.

If you need further help, feel free to ask. I'll probably also provide installation instructions for macOS in the documentation, soon.

**Comment by muellermartin** [comment]
As promised, I've added installation instructions for macOS in PR #123 :)

**Comment by muellermartin** [comment]
The guide in PR #123 seems to have resolved this question.

@algernon71 Feel free to close this issue then ;)

BTW: I saw this is your very first issue you opened on GitHub. Welcome to the community!

**Comment by florianfesti** [comment]
PR #123 has made it into the official docs: https://florianfesti.github.io/boxes/html/install/macos.html

Closing.
