### ISSUE TITLE
Need lid options on website

### ISSUE THREAD

**Issue by takkuso** [florianfesti/boxes#121]
On Universal Box, only choice for lids are for straight top_edge. When you change top_edge to anything else (Hinge Eye, Slide on Lid, Click On), no matching lid prints. You can choose a flat or chest lid, but they do not match the top_edge choice.

This is for https://www.festi.info/boxes.py
specifically, https://www.festi.info/boxes.py/UniversalBox

**Comment by florianfesti** [comment]
Yeah, looks like that call got dropped accidentally during the recent refactoring. Re-added.

Thanks for the report!

**Comment by takkuso** [comment]
Yep! Working now! Thanks so much
