### ISSUE TITLE
Feature idea: lids with handle

### ISSUE THREAD

**Issue by Blancanegra** [florianfesti/boxes#128]
A handle type like the one showed in the image helps to place both lid pieces in perfect place.

Depending on the lenght and quantity of perpendicular spikes (to the optional handle) you use, would make glue unnecesary for the lid.

![lid-handle](https://user-images.githubusercontent.com/32768345/54071652-cf67cc00-426f-11e9-8433-c689003ac689.jpg)

**Comment by florianfesti** [comment]
I am not quite getting how this is supposed to look on the bottom side. Do those parts go all out to the outside walls? Do you have a picture showing the underside?

**Comment by Blancanegra** [comment]
Sure, I just took some pictures showing different lids:

Top side:
![lids-top-side](https://user-images.githubusercontent.com/32768345/54188093-4c34b900-44af-11e9-94b2-a6acd3b99185.jpg)

Bottom side:
![lids-bottom-side](https://user-images.githubusercontent.com/32768345/54188121-5e165c00-44af-11e9-8824-4898916350f1.jpg)

Pieces for the lid of the first post image:
![lid1](https://user-images.githubusercontent.com/32768345/54188239-9322ae80-44af-11e9-99b7-f190517a778f.jpg)

Pieces for the lid of the hexagonal box:
![lid2](https://user-images.githubusercontent.com/32768345/54188353-c9f8c480-44af-11e9-8cd3-26f65eaa0366.jpg)

**Comment by florianfesti** [comment]
OK, I refactored the code for lids and added rectangular lids to all generators that really should have them. This includes infrastructure for handles. So far there is only one handle type supported and I don't have a good idea how to reuse the infrastructure for non rectangular boxes.
But adding more handle types and styles should be easy.

**Comment by florianfesti** [comment]
Still need user documentation and (i) links.

**Comment by Blancanegra** [comment]
Wow, those looks fantastic, thanks!
