### ISSUE TITLE
Box idea: sticky notes holder

### ISSUE THREAD

**Issue by Blancanegra** [florianfesti/boxes#129]
I'm not a coder but would be very easy to create a generator for this kind of open boxes, cloning and modifying the stackable edge a bit for given sides of the box, including a radius setting:

![Kajhuchäs-Notarj-custom3](https://user-images.githubusercontent.com/32768345/54740361-74ad6900-4bbb-11e9-8d32-0e03f730aa60.jpg)

Changing the size of the box it can hold sticky notes, business cards, napkins, etc . For napkins would be nice to have at least two opposite sides recessed.

Hope you like the idea!

**Comment by ffesti** [comment]
We actually already have one of those cut for beer coasters. But it was done using a UniversalBox edited with Inkscape. Writing a generator should be pretty easy.

**Comment by ZenithDK** [comment]
If you make the front a bit lower and add indents to the top sides, it
could even be stackable.

**Comment by florianfesti** [comment]
c09ee50fbd8c6c8b8671acf6163c5fecc9e16da8 adds a simple version. I might add settings to the slots so you can select the width and radius later on. 
Not quite sure if stacking them is that of an interesting feature. But it should be easy to do by overloading the StackableEdge instead of a straight Edge.

**Comment by florianfesti** [comment]
Any suggestions on the settings?

**Comment by Blancanegra** [comment]
The most common square notes from different brands are 76x76 mm in size (3x3 inches).
My settings are 78x78 mm (for easy notes replacement) and 35 mm inner height for that notes size.

**Comment by Blancanegra** [comment]
Testing notesholder.py and works fine, but  consider to add a slot holedistance parameter (together with width and radius) to make the wall stronger.

**Comment by bwente** [comment]
Seems to me the finger holes are too close to the slot using notesholder.py, maybe omit the finger holes under the slot?

**Comment by florianfesti** [comment]
Thinking a bit more leaving out the finger holes there is not really going to make a big difference. But having a cut out in the bottom will make it much easier to grab the last few sheets. But this requires cutting the front wall into two pieces.

**Comment by bwente** [comment]
But the finger holes keep breaking.

![image](https://user-images.githubusercontent.com/371964/60015639-f5b04c80-9651-11e9-9028-90bc6c04c2c6.png)

**Comment by Blancanegra** [comment]
> Thinking a bit more leaving out the finger holes there is not really going to make a big difference. But having a cut out in the bottom will make it much easier to grab the last few sheets. But this requires cutting the front wall into two pieces.

I prefer a strong wall than to easily keep the last few sheets. I'm modifying my notesholder with a slot to finger hole distance and making the slot wider up and narrow down:

![notesholder](https://user-images.githubusercontent.com/32768345/60015793-a20b2680-9684-11e9-9b0d-ade39e2da648.jpg)

**Comment by florianfesti** [comment]
Ok, I have finally re-done the NotesHolder to be fully split in the front. Change is not on the we instance yet. Feedback is welcome.

**Comment by bwente** [comment]
Here is a desktop object that I created using the new Nots Holder combined with a "skinny" tray.

![IMG_5516](https://user-images.githubusercontent.com/371964/90566586-beb2c980-e176-11ea-8697-584f273d6504.jpg)
