### ISSUE TITLE
Integrated Hinge Box - problem 

### ISSUE THREAD

**Issue by mackiavellipl** [florianfesti/boxes#130]
I have problem with IntegratedHingeBox on festi.info/boxes.py
When i click generate button (svg format) i receive message 
"This XML file does not appear to have any style information associated with it. The document tree is shown below."
Can anybody can help?

**Comment by Blancanegra** [comment]
Try to refresh the page until you get the render.

**Comment by florianfesti** [comment]
Duplicate of #136 
Well, actually the other way round, but 136 already has some explanation...
