### ISSUE TITLE
TypeTray isn't working

### ISSUE THREAD

**Issue by undercoverdesigns** [florianfesti/boxes#136]
The past few times I've tried to generate a TypeTray from https://www.festi.info/boxes.py/TypeTray, I get an empty document.  This happens even when I don't change any parameters from the initial setup.

**Comment by florianfesti** [comment]
Yeah, looks like my web server setup is still not stable enough. This is pretty annoying. Restarting the docker container solves the issue for a little while. Probably need to add a few more options to either apache or uwsgi *sigh*

**Comment by florianfesti** [comment]
Hope this works now. See #143 for details.
