### ISSUE TITLE
Pictures missing

### ISSUE THREAD

**Issue by THX2112** [florianfesti/boxes#140]
Many of the existing pictures are missing, and a lot of boxes don't have pictures or renderings. This makes it hard to figure out what the parameters do, or what the final box should look like without a lot of trial and error.

**Comment by florianfesti** [comment]
Yeah, making good pictures is difficult and a lot of work. I am especially bad at taking photos. So if you could take some and either open an PR or attach them here that would be a great help.

**Comment by Blancanegra** [comment]
I took some photos, please use it at your own convenience.

ElectronicsBox, and opened and closed:
![20191102115526_IMG_8703](https://user-images.githubusercontent.com/32768345/68070189-6dfaed00-fd6b-11e9-93b7-d438372c6b04.JPG)
![20191102114612_IMG_8696](https://user-images.githubusercontent.com/32768345/68070190-6e938380-fd6b-11e9-9bf0-213d4439ba66.JPG)

PaintStorage first version, stacked and with paint cans:
![20191102115936_IMG_8710](https://user-images.githubusercontent.com/32768345/68070199-a5699980-fd6b-11e9-8460-12bed88cd72f.JPG)

LaserHoldFast in action (ugly set but best than nothing):
![20191102114937_IMG_8699](https://user-images.githubusercontent.com/32768345/68070222-e19cfa00-fd6b-11e9-900a-f167b14a942c.JPG)

NotesHolder (default values):
![20191102115634_IMG_8704](https://user-images.githubusercontent.com/32768345/68070232-0db87b00-fd6c-11e9-84c0-44190c5bd6e3.JPG)

**Comment by florianfesti** [comment]
Thank you very much! Added as 9a8ae19 together with some picture of the WineRack I still had somewhere.

**Comment by florianfesti** [comment]
Ok, this ticket is kinda useless unless we actually track the missing pictures. So here's a list:

- BayonetBox
- Rack*Box
- FlexBox5
- HeartBox
- StorageRack
- Slatwall* - need a photo session in our wood workshop
- BurnTest
- ConcaveKnob
- FlexTest - could be rendered image
- FlexTest2 - could be rendered image
- GearBox
- Gears
- LBeam
- Planetary
- Planetary2
- Pulley
- RectangularWall
- WaivyKnob 
- AngledCutJig
- Arcade
- Display
- DrillBox
- Hook
- LaserClamp
- MagazinFile
- MakitaPowerSupply
- OttoLegs - get from Ottobot project page
- OttoSoles - get from Ottobot project page
- RoyalGame
- Rotary

**Comment by Wolfpuppie** [comment]
I took a picture of a 'console' box:

![07087016](https://user-images.githubusercontent.com/68129818/87205668-43086600-c308-11ea-9293-a96fac1fbba9.JPG)

here are some other angles: https://imgur.com/a/soQyL51

**Comment by florianfesti** [comment]
Thanks! See https://festi.info/boxes.py/Console?language=en for the new image!

**Comment by DiegoLascano** [comment]
has anyone built the rotary? it is kinda difficult to understand since there are lots of parts.

**Comment by florianfesti** [comment]
> has anyone built the rotary? it is kinda difficult to understand since there are lots of parts.

Yes. But as it currently is it's not that great and should probably be improved before anyone else builds one.
The contraption consists of 3 parts that are put on an aluminium profile:

At the very top of the drawing are the parts for the motor block. It has two rollers that are driven by an NEMA 23 stepper by a timing belt. The pulley for the motor itself is not included as the one I used already had one.

Below is a second block/box that is intended to hold the aluminium profile at the other end. Both of them have hooks to allow hanging the whole thing between to knifes of an knife table. This in theory saves a bit of usable height but in practice is just too much of an hassle and the hooks are too fragile anyway. So this pieces is not even needed.

The bottom half of the drawing (starting with the row of small rectangular pieces) is a scissor lift carrying to freewheeling rollers. The rollers are shown in the drawings but must be deleted before cutting. The problem is that the scissor lift is just too complicated and not rigid enough. One solution would be to just have a box with two rollers that slides on the aluminium profile and angle the whole thing instead of raising and lowering only the rollers.

The whole thing also misses a couple of features regularly found on professional rotary attachments like adjustable stops and rollers holding down the work piece.

If you want to build one I might just program some improvements. This is more likely to happen if you have an idea what features you want. Often making decisions on how things should look like are much harder than actually make them look that way. Alternatively you can just build the motor block twice and leave the rollers on the second block turning freely.

**Comment by florianfesti** [comment]
![Rotary](https://user-images.githubusercontent.com/3890249/90416311-99f51e00-e0b2-11ea-8b8e-6a65b3f93c10.jpg)
Here's a picture. I'll add it to the generator, too. It still doesn't show very clearly how the scissor lift is put together. But you really shouldn't anyway...

**Comment by Wolfpuppie** [comment]
Heartbox: https://i.imgur.com/PqfBcZX.jpg

**Comment by florianfesti** [comment]
> Heartbox: https://i.imgur.com/PqfBcZX.jpg

0403f01f0ed1c26d53848e739c641ba0b0f6eb88

Thanks for the picture!

**Comment by oscaracena** [comment]
These two may also be useful, although no the best quality...

![IMG_20200929_163557](https://user-images.githubusercontent.com/4654094/94573537-7c4ed300-0272-11eb-83fd-d0a3ecf95d00.jpg)
![IMG_20200929_163829](https://user-images.githubusercontent.com/4654094/94573541-7d800000-0272-11eb-9627-4b216c08398a.jpg)

**Comment by florianfesti** [comment]
> These two may also be useful, although no the best quality...> 
Well, still a lot better than no image at all. Added as 928e88f070ffcf14d3afc364408dfe92d99e5cb2 Will update the web instance soon.
Thanks a lot!

**Comment by Blancanegra** [comment]
Some shots and comments:

BayonetBox
![BayonetBox](https://user-images.githubusercontent.com/32768345/95308409-25f11e00-088a-11eb-9458-6fde48d4ee7f.jpg)

Placing perimetral holes to insert metal wire or wood sticks would be helpful for aligning the segments when gluing them.

![BayonetBox-segment-aligment-holes](https://user-images.githubusercontent.com/32768345/95309304-41a8f400-088b-11eb-8e3b-c576e1c07849.jpg)


BasedBox
![BasedBox](https://user-images.githubusercontent.com/32768345/95308442-32757680-088a-11eb-8290-f136e83d368d.jpg)

Would be possible to add an option to customize the base size (hole distance?)?

LBeam
![LBeam](https://user-images.githubusercontent.com/32768345/95308463-3903ee00-088a-11eb-9f7f-97cae1b6fc98.jpg)

In some cases like that, is not easy to figure what x, y and h parameters really are, so I engraved those in the corresponding sides for the picture.

**Comment by impellerturn** [comment]
Hi,
here some pictures of StorageRack:
![P1050181_cut](https://user-images.githubusercontent.com/42349199/103280803-96af5e80-49d1-11eb-86b9-abd94555421c.jpg)
![P1050183_cut](https://user-images.githubusercontent.com/42349199/103280807-99aa4f00-49d1-11eb-9b35-72eb846f61e1.jpg)
![P1050186_cut](https://user-images.githubusercontent.com/42349199/103280811-9b741280-49d1-11eb-8b6c-1bece3a7dc6c.jpg)
Best regards

**Comment by florianfesti** [comment]
Thank you very much! Added with e6dccc413555817335786a815b42b57153039b83

**Comment by Arcturuss** [comment]
> In some cases like that, is not easy to figure what x, y and h parameters really are, so I engraved those in the corresponding sides for the picture.

> Yes, I should rename all the dimensions at some point to meaningful names.

Maybe it'll be more useful to show all dimensions on photo or drawing, especially in generators that are not so obvious. 
smth like this:

![BinTray1](https://user-images.githubusercontent.com/465493/111915757-f07f6c00-8a88-11eb-9b0f-06c4399d2524.jpg)

**Comment by ClaneSharke** [comment]
Images for Angle Cut Jig
![WhatsApp Image 2021-06-18 at 19 12 13](https://user-images.githubusercontent.com/22819500/122595893-6172f780-d069-11eb-84ea-a969b164000e.jpeg)
![WhatsApp Image 2021-06-18 at 19 12 13 (1)](https://user-images.githubusercontent.com/22819500/122595898-633cbb00-d069-11eb-8460-301cd5f77096.jpeg)
![WhatsApp Image 2021-06-18 at 19 12 13 (2)](https://user-images.githubusercontent.com/22819500/122595900-633cbb00-d069-11eb-828d-a2670153017e.jpeg)
![WhatsApp Image 2021-06-18 at 19 12 13 (3)](https://user-images.githubusercontent.com/22819500/122595902-63d55180-d069-11eb-9645-233c0c3f7a9c.jpeg)
![WhatsApp Image 2021-06-18 at 19 12 13 (4)](https://user-images.githubusercontent.com/22819500/122595905-646de800-d069-11eb-806b-0b245cf74d39.jpeg)

**Comment by tzwilliams** [comment]
Love the tool!! Here are two **RoundedBox** images showing different `edge` styles.

Default: `edge_style = f Finger Joint`
![boxes py  RoundedBox  fingerJoint, 80x80x100mm  open](https://user-images.githubusercontent.com/27858774/134699528-3e6da151-2293-4db2-875a-6c7c48ad0d90.jpg)

Alt: `edge_style = h Edge (parallel Finger Joint Holes)`
![boxes py  RoundedBox  EdgeJoint, 90x90x100mm  open](https://user-images.githubusercontent.com/27858774/134699546-ef6da021-c0f6-4a51-998e-1a4e9759cacf.jpg)

**Comment by tzwilliams** [comment]
Some additional ShutterBox images (using the spring finger joint option and with sanded corners)
![PXL_20210924_152626953-01](https://user-images.githubusercontent.com/27858774/134702528-fc4296f1-3afb-4117-92d6-f810381aba1c.jpeg)
![PXL_20210924_152529664-01](https://user-images.githubusercontent.com/27858774/134702534-8404b828-17e4-4266-8721-3a5ba0d19298.jpeg)
![PXL_20210924_152222185](https://user-images.githubusercontent.com/27858774/134702546-c83e26c7-552d-43ed-923a-f936c56c850e.jpg)

**Comment by florianfesti** [comment]
Added with d6c8d965c3a4bca7c88739774161f1ab281c44ce and cbbe8c11cc781fade7286ec323f5a93798269075

@tzwilliams : I kept the original image for the ShutterBox as it shows an un-sanded example. That's a bit of a shame as your picture is much better. But the old one fits better into the sample pictures which are all un-sanded.

Anyway, thanks for these very nice pictures!

**Comment by tzwilliams** [comment]
@florianfesti, my pleasure.  I agree with keeping the old pictures--I think they each show useful information.  I'll try to keep contributing pics as time allows :)

**Comment by profparedes** [comment]
TriangleLamp

**Comment by Day0Dreamer** [comment]
TwoPiece
![IMG_20220412_215245](https://user-images.githubusercontent.com/11721610/163043425-de790435-0b7a-4fe6-bd50-50c6be688326.jpg)
![IMG_20220412_215322](https://user-images.githubusercontent.com/11721610/163043441-5dd29255-433a-42fb-bb04-c6840029c53f.jpg)
![IMG_20220412_215357](https://user-images.githubusercontent.com/11721610/163043454-26a9252d-984a-4d27-acbb-cf6b71b207a0.jpg)

**Comment by vinicius-bianco** [comment]
Hi, i don't spend a lot of time doing this, so the render isn't good. I will try to make a better render, but maybe this one is useful... here is my default Drill Box, rendered in eevee, blender.
![DrillBox](https://user-images.githubusercontent.com/72886064/166071967-2408bf80-e63a-4797-b381-0e4bd52581a6.jpg)

**Comment by florianfesti** [comment]
> Hi, i don't spend a lot of time doing this, so the render isn't good. I will try to make a better render, but maybe this one is useful... here is my default Drill Box, rendered in eevee, blender. ![DrillBox](https://user-images.githubusercontent.com/72886064/166071967-2408bf80-e63a-4797-b381-0e4bd52581a6.jpg)

This is "assembled" upside down. The larger ridge should be at the top, to give a bit of protection to the drills. Otoh there is not much use to have this amount of space below the bottom.

**Comment by florianfesti** [comment]
> Images for [drillstand ](https://www.festi.info/boxes.py/DrillStand?language=en) with some steps for assembly. Careful with the orientation of the bottom part (B), it's slightly asymmetrical.

Added your pictures to the description. Thanks a lot! This makes assembly a lot easier to understand.
Turned out I actually had added a sample image a while a go but with the wrong name m)

**Comment by florianfesti** [comment]
> TwoPiece, default settings 10cm x 10cm x 10cm outer borders; 2.5mm thick

Added one of the pictures to the description - together with a bit help on the `hi` param. As the box is very simple it does not really justify more images. Still thanks!

**Comment by vinicius-bianco** [comment]
> 
:)
![DrillBox2](https://user-images.githubusercontent.com/72886064/166553530-f5dbc597-608f-4d31-be27-8488f6e0929c.jpg)

**Comment by vinicius-bianco** [comment]
> > Hi, i don't spend a lot of time doing this, so the render isn't good. I will try to make a better render, but maybe this one is useful... here is my default Drill Box, rendered in eevee, blender. ![DrillBox](https://user-images.githubusercontent.com/72886064/166071967-2408bf80-e63a-4797-b381-0e4bd52581a6.jpg)
> 
> This is "assembled" upside down. The larger ridge should be at the top, to give a bit of protection to the drills. Otoh there is not much use to have this amount of space below the bottom.

fixed and improved :)

![DrillBox3](https://user-images.githubusercontent.com/72886064/166556058-1a722802-9b52-4035-824a-d7a115b3423c.jpg)

**Comment by HaSHsss** [comment]
Made  in Photoshop  for `AllEdges.py` generator

![AllEdges](https://user-images.githubusercontent.com/63124812/172206652-0a8a6eac-fbfb-4833-8b6c-8af6defb2e8e.jpg)

**Comment by florianfesti** [comment]
Thanks! Added with 4344c93b6ef. Will update the web instance as soon as I am back home. Don't want to touch it while being at the airport.

**Comment by florianfesti** [comment]
Added with aba88f3e1da9e572cf5578536cfa5b3b39439f2b. Thanks a lot!

**Comment by ednisley** [comment]
A small BreadBox:

![PXL_20221130_204041166 - Rolltop cupcake box - closed](https://user-images.githubusercontent.com/599600/204935168-b3227855-7c0e-4338-b315-0f8bcca4142e.jpg)

The door works great:

![PXL_20221130_204110900 - Rolltop cupcake box - open](https://user-images.githubusercontent.com/599600/204935295-63fa9539-cfb9-492a-9dfd-a8ca3b7dfe20.jpg)

A few more details on [my blog](https://softsolder.com/) at https://softsolder.com/2022/12/01/rolltop-cupcake-box/

**Comment by florianfesti** [comment]
Oh, this post got lost in pre x-mas rush. Finally added with d3df27b238db27310b42e801b25926184fd4985a
Cutting and taking pictures of new generators is super helpful. Thanks @ednisley !

**Comment by florianfesti** [comment]
@eoto88 Added as 71e23910ccf47b566bd62326566ce034fd56be80 

Thanks for the picture!

**Comment by d5e** [comment]
**Drillbox**.

Made of 3mm MDF with a 150W CO2-Laser. Glue-Free :)

![IMG20230223150501](https://user-images.githubusercontent.com/397599/221385884-3dec8b5d-3e69-436d-bfc9-cd781b0565f1.jpg)

**Comment by florianfesti** [comment]
Added with 0e4e373367059cd165562cb6f1a8e0c86f43ee32. Thanks for the picture!

**Comment by datazaShane** [comment]
ConcaveKnob
![CurvedKnob3](https://user-images.githubusercontent.com/69878114/228815247-75b3dfb6-30dc-488b-bfb9-21a57643439b.jpeg)
![CurvedKnob2](https://user-images.githubusercontent.com/69878114/228815261-ac7843f0-df34-468d-ad22-097d8d027b78.jpeg)
![CurvedKnob1](https://user-images.githubusercontent.com/69878114/228815264-9f7d4581-e333-4b44-a996-885bcef4201c.jpeg)

**Comment by datazaShane** [comment]
Laptop Stand
![Laptop Stand 2](https://user-images.githubusercontent.com/69878114/228819383-c17db841-1b56-4999-96c4-ed37d49c1759.jpeg)
![Laptop Stand 1](https://user-images.githubusercontent.com/69878114/228819396-7abc73fd-9b04-4dc0-85ec-54efeb6c0faa.jpeg)

**Comment by datazaShane** [comment]
Used Drillbox Template to make box for Router Bits
![Router Bit Box](https://user-images.githubusercontent.com/69878114/228819874-b6f6d210-6abf-4608-8969-e4c82043ec5e.jpeg)

**Comment by datazaShane** [comment]
Hook
![hook 1](https://user-images.githubusercontent.com/69878114/233830649-048b11c8-55b9-4251-8a77-6ec5bdd439a2.jpg)
![hook2](https://user-images.githubusercontent.com/69878114/233830654-5b5b5731-3dc1-4af5-89cf-3b92292464a0.jpg)

**Comment by florianfesti** [comment]
Hmpf, guess Ad with one "d" work here, too...

**Comment by PhoenyxAshe** [comment]
I just cut and partly assembled a small version of the triangle lamp, and once I've had a decent sleep and figured out the probably quite obvious steps I'm missing, I'll post the updated version.  I'm guessing either dowels in the screen holes and a flexible material wrapped around, or screen panels between the two ends?  Both?
![20230502_010422](https://user-images.githubusercontent.com/102438319/235602530-5e4364ee-b3a8-4e2f-b7ae-c8aaec6c6f7c.jpg)

**Comment by florianfesti** [comment]
> I'm guessing either dowels in the screen holes and a flexible material wrapped around, or screen panels between the two ends? Both?

Yeah, this generator is clearly missing some documentation. It was done as a project for another institution and ofc they knew what they wanted to do...

**Comment by florianfesti** [comment]
Ehm, I mean: The idea is to use translucent acrylic for the top triangle and screw that in place. The screws should pass through the top layer but bite into the little wooden triangles underneath. IIRC they also added connectors to the sides so that multiple triangle lamps could be connected to a larger installation.

**Comment by BeppieTheKlapp** [comment]
Got two
![Afbeelding van WhatsApp op 2023-11-18 om 15 49 02_82c91720](https://github.com/florianfesti/boxes/assets/17335918/d6c7d970-f965-4f8c-bcfe-6d1f26c6bd8e)
![Afbeelding van WhatsApp op 2023-11-18 om 15 49 02_d853b66c](https://github.com/florianfesti/boxes/assets/17335918/f15469ac-57dc-4910-8ca4-f0412c09d17c)
for the 7-segment digit display:

**Comment by crashnbernstein** [comment]
Pin Rack render
![PinRack v2](https://github.com/florianfesti/boxes/assets/63522634/99b14c81-6dc2-4f34-9a48-0437dcb2d6be)

**Comment by florianfesti** [comment]
Added with 10012e596694ecd9ce Thanks!

**Comment by florianfesti** [comment]
This is getting too long and unwieldy. Created a new issue for this: #628
