### ISSUE TITLE
Fix outside param for arbitrary edge types

### ISSUE THREAD

**Issue by florianfesti** [florianfesti/boxes#144]
TypeTray and StorayShelf (see #142) do support the `outside` param but it does not work properly for most edge types. UniversalBox actually should also have a `outside` param but has not to avoid this very problem. The code should use the actual width of the edges to correct the sizes.

**Comment by sgtpepperaut** [comment]
tyring to create a simple open box (without a lid) with outside dimensions without having todo math.. :) any chance we can get that checkbox is there?
