### ISSUE TITLE
Feature: 3D preview

### ISSUE THREAD

**Issue by matthijskooijman** [florianfesti/boxes#145]
It would be interesting if boxes.py could render a 3D preview. For complex boxes, this could help a lot to see what a box looks like, and during development to see if things are lining up correctly.

For this to work, you would need some kind of 3D rendering library that can import the 2D parts, extrude them to thickness and arrange them in a 3D view. Most of this is generic, except the arranging which has to be done by each generator individually.

Having a 3D preview might also help for #140 (though actual pictures of finished products are probably nicer).

**Comment by florianfesti** [comment]
I doubt this is actually possible with the project right now. The parts are not really properly closed lines. This project was deliberately done aiming for 2D only. For a 3D preview it is probably easier to start a new box generator based on a different technology all together.
