### ISSUE TITLE
Missing translation file.

### ISSUE THREAD

**Issue by greenaar** [florianfesti/boxes#169]
With the current HEAD, the following error occurs when trying to build/install.

12:05:04 creating build/bdist.linux-x86_64/egg/share/locales/zh_CN/LC_MESSAGES
12:05:04 error: can't copy 'locales/zh_CN/LC_MESSAGES/boxes.py.mo': doesn't exist or not a regular file

The command being run which generates this error is:

/opt/boxes/bin/python setup.py build &&  /opt/boxes/bin/python setup.py install

**Comment by Rotzbua** [comment]
maybe thats the problem:
doesnt exist: `locales`
exist: `locale`

**Comment by greenaar** [comment]
Confirmed fixed.

**Comment by florianfesti** [comment]
Thanks for reporting and testing!
