### ISSUE TITLE
Inkscape extension errors on Linux

### ISSUE THREAD

**Issue by juleswh** [florianfesti/boxes#171]
After installing with `sudo setup.py install` from a fresh git clone, running inkscape from the console produces the following error:

```
/usr/share/inkscape/extensions/boxes.py.DisplayShelf.inx:14: parser error : AttValue: " or ' expected
      <param name="outside" type=boolean max="9999" _gui-text="outside" gui-desc
```
And many similar ones (missing " around the type attribute values).

The following command solved the problem:
```
sudo sed -i -e "s/type=\(\w*\) /type=\"\1\" /g" /usr/share/inkscape/extensions/boxes.py.* 
```

----
I'm on Linux Mint 19.1, with Inkscape version 0.92.3, using only packages from the default package manager.

----

Thanks for this good piece of software!

**Comment by florianfesti** [comment]
Thanks for debugging and reporting this!
