### ISSUE TITLE
Custom fingers/edges

### ISSUE THREAD

**Issue by Skivmag** [florianfesti/boxes#177]
I'm looking for a way to redefine standart fingerhole connect with something like on the picture:
![Image of Spike connection](https://i.imgur.com/D5SZ8mk.jpg)
It allows to assemble box without clue
Does it exist simple way to do it?

**Comment by ZenithDK** [comment]
Support for this would be awesome. I've bought a number of board game inserts with this kind of finger joints and it works great.

**Comment by florianfesti** [comment]
The longer I think about it the easier this seems to be. I'll give it a try the next time when I am at the laser cutter.

**Comment by florianfesti** [comment]
Code is not on the web instance yet. Can someone try with a local instance if the result is as it should be, please? In my small test with 3mm it worked just fine. But I am not sure if it will really work with something like acrylic.

**Comment by bferrarese** [comment]
Trying inkscape extension Misc/AllEdges and I don't see it. I'm guessing the .inx don't have the new option.

**Comment by bferrarese** [comment]
Got it working by manually setting 'springs' in my inx

![Screenshot from 2019-10-11 16-28-16](https://user-images.githubusercontent.com/47937307/66686221-55a02280-ec44-11e9-80ac-42cbe73bbb16.png)

**Comment by Skivmag** [comment]
Today tried on master branch
Works like a charm, thank you!
I'll try it to cut it on Tuesday and will write about results
