### ISSUE TITLE
difference between TrayLayout and TrayLayout2?

### ISSUE THREAD

**Issue by blackmad** [florianfesti/boxes#179]
What's the difference between these two classes/generators? It's not very clear from the description or from the code/comments

 *  TrayLayout  -  Generate a typetray from a layout file
 *  TrayLayout2  -  Generate a typetray from a layout file

(also confused why the web UI only seems to show TrayLayout, when then both have webui set to true)

**Comment by florianfesti** [comment]
Yeah, that should probably pointed out more clearly in the comments. TrayLayout is special as it is a two step process. TrayLayout creates a skeleton layout file to which you can add the measurements. TrayLayout reads that in and turns it into an actual drawing.
There is special code in the web instance to make this work.
So https://festi.info/boxes.py/TrayLayout?language=en has only x and y as parameters. The result is a TrayLayout2 form with `layout` set accordingly.
