### ISSUE TITLE
ShutterBox: blank output when "reference" is set to blank instead of 100

### ISSUE THREAD

**Issue by dlarue** [florianfesti/boxes#180]
Great Project!
I was generating the ShutterBox with 100 x 75 x 75 size and tried to remove the reference box by making it blank and the result was no generated output. When I put 100 back it generated normally.

**Comment by florianfesti** [comment]
Yeah, as `reference` is a float argument it needs to be 0 and an empty string is not allowed. But another errors swallowed the error message that should be displayed in that case.

Fixed. Thanks for reporting!
