### ISSUE TITLE
Noteholder is not working as expected

### ISSUE THREAD

**Issue by tschissler** [florianfesti/boxes#187]
First, I'd like to mention that I was surprised that the behavior of the noteholder box changed completely. In the past I was able to create these kind of boxes which is not possible anymore.
![image](https://user-images.githubusercontent.com/11467601/68104885-1086ad80-fedd-11e9-9d98-9c8c43c87ae4.png)
I'd like to kindly ask to create new types for a change in behaviour.

Second thing is that it seems to have a bug: 
![image](https://user-images.githubusercontent.com/11467601/68104937-40ce4c00-fedd-11e9-8a5e-6cf2cb793d3d.png)

**Comment by florianfesti** [comment]
Yes, the behavior was changed as of #129. The issue above is only showing up for opening == 0.0 which is not really proper use of the generator. But as I added special code for this case let me fix that code quickly.

**Comment by florianfesti** [comment]
The new design can now be seen in the thumbnail.
