### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by PellelNitram** [florianfesti/boxes#191]
I have troubles reaching https://www.festi.info/boxes.py/ (as well as https://www.festi.info/).

Are they maybe down?

**Comment by jessyjones** [comment]
Same for me, I was in the middle of cutting some boxes 😐

**Comment by ffesti** [comment]
Ok, restarted the service. Should work again. Need to fix the remaining backtraces at some point that make the serivce lock up after enough workers have failed. There are still several inputs left that allow the code to fail.

**Comment by florianfesti** [comment]
Ok, I just put a big try except block around everything. No idea why I didn't do that from the beginning...

**Comment by jessyjones** [comment]
Thank you so much!!
