### ISSUE TITLE
dovetailjoint 

### ISSUE THREAD

**Issue by msngnj** [florianfesti/boxes#194]
HI - first of all thank you for this wonderful script.

I need to add some "play" with "dovetail joint" for "RoundedBox".
because it's too fit and break the 3mm MDF when assembled.
how can i do that?

**Comment by florianfesti** [comment]
There isn't a way to do that for dovetails only, right now. But you can lower the value of `burn` to get all joints a bit more lose. The default of 0.1 is pretty stiff for most materials on a decent laser cutter. You can use the new [BurnTest](https://festi.info/boxes.py/BurnTest?language=en) generator to try out different values - although it only does finger joints.
