### ISSUE TITLE
generate.sh has reference to missing box generator

### ISSUE THREAD

**Issue by christensonb** [florianfesti/boxes#208]
```
+ ../scripts/boxes box --x=50 --y=50 --h=70 --output=box.svg
Unknown generator 'box'. Use boxes --list to get a list of available commands.
```

**Comment by christensonb** [comment]
--version doesn't work
--help only works if a <generator> is supplied

**Comment by florianfesti** [comment]
Yeah, this has experienced quite some bit rot. May be the script needs to be redone to just execute `--list` and then run all generators. There was the idea to make this into a test suite. But that never really happened. One issue is that the resulting file change easily.
Not really sure what to do this this right now...

**Comment by florianfesti** [comment]
Still thanks for pointing out that *something* should be done about this.

**Comment by christensonb** [comment]
Even still I like this code base ALOT, thanks for writing it.
