### ISSUE TITLE
Extensions grayed out and unusable in Inkscape on Mac OSX Catalina

### ISSUE THREAD

**Issue by dubchild** [florianfesti/boxes#212]
I finally got the extension menu installed without errors and it shows up but they are all GRAY. I have updated everything and jumped through a million hoops. I have read all there is to read on this script and I am about to throw in the towel because I've wasted so much time on it. It would be really helpful to make a quick video of installation on all platforms because this thing is quite needy and fragile. 

I have spent more than 6 hours trying to get this script to work in inkscape. The web version is great but the promise of running it locally inside inkscape was enough to make me jump in. Please help.

**Comment by florianfesti** [comment]
They are greyed out then the .inx files are found but the boxes script is not. Place a copy or a symlink into the extensions directory where the .inx files are.

**Comment by dubchild** [comment]
Thanks for your response. However, as you can see in the screenshot, the boxes script is already right there with the .inx files and it doesn't work.

<img width="579" alt="Screen Shot 2020-03-04 at 3 05 58 PM" src="https://user-images.githubusercontent.com/4512211/75918505-db0db480-5e29-11ea-8e1b-76567b11d089.png">

**Comment by florianfesti** [comment]
Can you try removing the following line from one of the inx files:

`<dependency type="executable" location="path">boxes</dependency>`

**Comment by dubchild** [comment]
I removed that line from boxes.py.AllEdges.inx and restarted inkscape. Still grayed out. Am I supposed to do something else?

**Comment by florianfesti** [comment]
Hmm...
Ok, as we are desparate: Try to also remove

```
  <script>
    <command reldir="extensions">boxes</command>
  </script>
```
at the bottom of the file. If this still doesn't show a menu you are editing the wrong file.
Ofc this will make the plugin not do anything but we need the UI to show up first.

**Comment by dubchild** [comment]
Nothing changed. I'm editing the files at Inkscape.app>Contents>Resources>share>inkscape>extensions. If not those files, which path should I be looking at?

**Comment by florianfesti** [comment]
`inkscape -x` gives the path inkscape looks for extensions.

**Comment by jandion** [comment]
I just had the same issue, I managed to fix it by adding the directory where I have the boxes file to the path system variable. It worked on Windows 10, but I guess it will be the same on mac or linux

**Comment by dubchild** [comment]
Yeah I tried that on my macbook and it didn't change anything. Maybe i'm doing it wrong but i added it to my path and still no love. I guess i'm just going to run the local server and load the output manually which is what I was trying to avoid doing. Inkscape is a huge turn-off anyway. I have Illustrator and Affinity which I'm much more comfortable with. 

Boxes.py is great, but the Inkscape plugin setup definitely needs some work. Only the most technical and dedicated users will ever figure it out. I had 2 other professional coders look at it and they couldn't figure it out either. I understand it's free software, but at the same time I'm really disappointed.

**Comment by Moini** [comment]
Here's the documentation for updating Inkscape extensions for Inkscape 1.0:
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0

For remaining questions regarding how to update, visit https://chat.inkscape.org/channel/inkscape_extensions .

**Comment by jgforbes** [comment]
Any resolution for the grayed out issue?
I am getting the same thing on  Fedora 33 with a fresh installation of inkscape and latest version of boxes.py.

**Comment by chill117** [comment]
So I ran into the same problem described in this issue. After a lot of trial and error, I finally got it working by:
* Copying the `.inx` files located at `./inkex/*.inx` to `~/.config/inkscape/extensions/`
* Copying the boxes script located at `./scripts/boxes` to ~/.config/inkscape/extensions/`
* Adding the inkscape extensions directory to my user's path - e.g:
```bash
echo $'\nexport PATH=$PATH:~/.config/inkscape/extensions' >> ~/.profile && source ~/.profile
```

**Comment by neophrema** [comment]
Im not sure, I followed what you suggest, I still get kind of an error, and its still grayed out, not sure if this is related:

```
** (org.inkscape.Inkscape:5114): WARNING **: 13:53:58.166: Image file ('/home/plato/.config/inkscape/extensions/./WineRack-thumb.jpg') not found for image widget in extension 'info.festi.boxes.py.WineRack'.
Shortcut::read: invalid verb: DialogSpellcheck
```

**Comment by florianfesti** [comment]
boxes_proxy.py got added to the repo a while a go. So this should work now. Please reopen if things are still broken.
