### ISSUE TITLE
parseArgs unusual inkscapefile

### ISSUE THREAD

**Issue by christensonb** [florianfesti/boxes#215]
within boxes/__init__.py
```
    def parseArgs(self, args=None):
        """
        Parse command line parameters

        :param args:  (Default value = None) parameters, None for using sys.argv

        """
        if args is None:
            args = sys.argv[1:]
        if len(args) > 1 and args[-1][0] != "-":
            self.inkscapefile = args[-1]
            del args[-1]
            if args[-1] == '--output':
                del args[-1]
```
This is saying treat the last command line argument as a positional argument for inkscapefile.
This is very odd and breaks using command line arguments.
What are you trying to do here?

**Comment by florianfesti** [comment]
The boxes binary is used for the Inkscape plugin. This code is there to deal with the special params Inkscape passes down to us. It's a bit of a hack that can probably be done better.
