### ISSUE TITLE
Traylayout2

### ISSUE THREAD

**Issue by christensonb** [florianfesti/boxes#216]
I want to have a joint that can service multiple pieces coming together
The closest I can find is the Traylayout2, but I have no idea what this svg is doing.

https://www.festi.info/boxes.py/TrayLayout2?FingerJoint_angle=90.0&FingerJoint_style=rectangular&FingerJoint_surroundingspaces=2.0&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&h=100.0&hi=0.0&outside=0&outside=1&layout=+%2C%3E+0.0mm%0D%0A+%7C+%2C%3E+0.0mm%0D%0A%2B-%2B-%2B%0D%0A%7C+%7C+%7C+0.0mm%0D%0A%2B-%2B-%2B%0D%0A%7C+%7C+%7C+0.0mm%0D%0A%2B-%2B-%2B%0D%0A&thickness=3.0&format=svg&tabs=0.0&debug=0&reference=100&burn=0.1&render=1

**Comment by florianfesti** [comment]
The TrayLayout is the only generator that does not create a proper box without adding some numbers. If you do you can create something like this:

https://www.festi.info/boxes.py/TrayLayout2?FingerJoint_angle=90.0&FingerJoint_style=rectangular&FingerJoint_surroundingspaces=2.0&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&h=100.0&hi=0.0&outside=0&outside=1&layout=+%2C%3E+40.0mm%0D%0A+%7C+%2C%3E+50.0mm%0D%0A+%7C+%7C+%2C%3E+40.0mm%0D%0A%2B-%2B-%2B-%2B%0D%0A%7C+%7C+++%7C+30.0mm%0D%0A%2B-%2B-%2B-%2B%0D%0A%7C+%7C+%7C+%7C+40.0mm%0D%0A%2B-%2B+%2B-%2B%0D%0A%7C+%7C+%7C+%7C+40.0mm%0D%0A%2B-%2B-%2B-%2B%0D%0A&thickness=3.0&format=svg&tabs=0.0&debug=0&reference=100&burn=0.1&render=1 (remove the "render=1" at the end to see the settings)

As you can see it uses a combination of finger joints for corners and T junctions and slots for crossings of walls. Right now Boxes.py does not support a joining 3 pieces (or four) out of the box.

You can instantiate your own set of FingerJointEdges that have half length fingers or create your own asymmetrical Edge type. There are actually a few generators that could use such edges.
