### ISSUE TITLE
Problems with box of console type generation

### ISSUE THREAD

**Issue by st-stalker** [florianfesti/boxes#224]
Today i tried to cut console [here's setup](https://www.festi.info/boxes.py/Console?FingerJoint_angle=90.0&FingerJoint_style=rectangular&FingerJoint_surroundingspaces=0.5&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&Stackable_angle=60&Stackable_height=2.0&Stackable_holedistance=1.0&Stackable_width=4.0&x=100&y=120&h=100&hi=50&angle=60&thickness=4.0&format=svg&tabs=0.0&debug=0&reference=100&burn=0.1&render=1) - but in the end i couldn't fit back panel - the tabs was overlapping. I can't find a way where I could make mistake, so i assume, that there could be mistake in the code.

Here's photos of the result: ![pic1](https://user-images.githubusercontent.com/12448943/80846168-194e0700-8c14-11ea-8f76-248bbcc6d49e.jpg)
![pic2](https://user-images.githubusercontent.com/12448943/80846171-19e69d80-8c14-11ea-900b-7f529c62b06a.jpg)

I wanted to make more cool photos to submit, but... seems, I'll do it next time.

**Comment by florianfesti** [comment]
Yeah, there is a bug. For uneven number of walls the parts can't just all have the same edge on both sides. Give me a few minutes and I'll try to fix that.

**Comment by florianfesti** [comment]
Ok, fixed in 949c8d8324b1454b7f77a1a78dd106064238a755. It should be enough to just re-cut the back wall as everything else is unchanged (right-most part).
 Sorry for the inconvenience!

**Comment by florianfesti** [comment]
Yeah, making good photos is tricky especially of transparent pieces like this. Having a good picture for the generator would be really great.

**Comment by florianfesti** [comment]
OK, closing this ticket as everything seems fine now. If you still have some good photos you can still attach them here or open a new ticket or PR.
