### ISSUE TITLE
BottleStack 'Double' option

### ISSUE THREAD

**Issue by QuitButton** [florianfesti/boxes#225]
This isn't really an issue, other than me being stupid, but I can't see how the 'double' option on the BottleStack fits together. The non-double option is obvious, I just can't see how to make a double width one. 

Is there a photo or even a basic drawing to put my mind at rest?

**Comment by QuitButton** [comment]
![20200505_211002](https://user-images.githubusercontent.com/7461614/81111587-384ee080-8f15-11ea-9e58-6cb5831d31cc.jpg)

Is that right?

**Comment by florianfesti** [comment]
Yes, exactly. And you can put them together in any width from 2 to 4 bottles.

**Comment by florianfesti** [comment]
Well, 3 to 10 bottles if you also stack upwards
