### ISSUE TITLE
Gears broken

### ISSUE THREAD

**Issue by bbphd** [florianfesti/boxes#228]
### (Bug!) Trying to generate [Gears](https://festi.info/boxes.py/Gears?teeth1=12&shaft1=6.0&dpercentage1=75&teeth2=32&shaft2=0.0&dpercentage2=0&modulus=5&pressure_angle=20&profile_shift=20&thickness=3.0&format=svg&tabs=0.0&debug=0&reference=100&burn=0.1&render=1) on website using default parameters or any other parameters I tried just gave an error.
[Gearbox ](https://festi.info/boxes.py/GearBox?FingerJoint_angle=90.0&FingerJoint_style=rectangular&FingerJoint_surroundingspaces=2.0&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&teeth1=8&teeth2=20&modulus=3&shaft=6.0&stages=4&thickness=3.0&format=svg&tabs=0.0&debug=0&reference=100&burn=0.1&render=1 )works well but does not support D shafts (and the default parameters are a bad choice because if you make it you'll get little gear teeth falling off the gears and falling down into your bed).

**Comment by florianfesti** [comment]
Turns out the gears are just fine. But the text implementation in the new back end has still issues. Well, now one less.

Thanks for reporting!

**Comment by bbphd** [comment]
Thanks I will try it!
