### ISSUE TITLE
Corrections for InkScape 1.0

### ISSUE THREAD

**Issue by vmario89** [florianfesti/boxes#231]
Hi,

running InkScape extensions i get some unclean warnings from console which could be fixed

* one fix is to convert True to true and False to false
* another fix: boxes.py.RectangularWall.inx
```
<item value="M">M Edge for slide on lid (box left)</item>
```
this entry is duplicate per data set 4 times

additionally console puts out a lot warnings like "Attempting to translate an empty string in extension 'info.festi.boxes.py.UniversalBox', which is not supported." but i am not sure how to omit them. It has to do with parameters starting with "_" like _name or _gui-text

**Comment by florianfesti** [comment]
Thanks for reporting!

The Inkscape extensions still need a bit more love. `inkscape -x` is no longer supported and there is some smarter way needed whether we build for the system or the user directory (and then use `--user-data-directory` or `--system-data-directory` respectivly).
I also have the sneaking suspicion that the `<script>` and `<dependency>` tags needs a second thought to work cleanly for all kind of installations - especially when including Windows and Mac.
