### ISSUE TITLE
Storageshelf with top as bottom

### ISSUE THREAD

**Issue by csreades** [florianfesti/boxes#244]
It would be great to have the option to have the top of the storageshelf to be same as the bottom (with the additional panel included). 

So a lid that is included.

**Comment by florianfesti** [comment]
I am not quite sure if I understand what you want.

Doesn't top_edge allow you to create a top when selecting "f finger joint". Or would you want to have a "h" edge there, too?

Or are we talking about a completely different part of the shelve?

**Comment by csreades** [comment]
Forgive me I didn’t see that the f was there. However yes it would be good if it had the h option also?

**Comment by florianfesti** [comment]
Ok, let's hope this doesn't break anything.
