### ISSUE TITLE
Display corners overlap

### ISSUE THREAD

**Issue by gcollic** [florianfesti/boxes#248]
"Display" has some corners overlapping other elements.
It looks like a regression in roundedPlate.
I'm not currently on my computer, I can't dig deeper right now, but I wanted to create the issue before forgetting.

Test case : https://www.festi.info/boxes.py/Display?x=150.0&h=200.0&radius=5.0&angle=0.0&thickness=3.0&format=svg&tabs=0.0&debug=0&reference=100&burn=0.1&render=1

The problem was seen in a video: https://youtu.be/Ud6JzZ_RGN8

**Comment by florianfesti** [comment]
Thanks for reporting!

I guess there is still something else wrong with the new `roundedPlate()` code. But this fix makes the issue go away.
