### ISSUE TITLE
Option to remove "burn correction" for milling

### ISSUE THREAD

**Issue by ottobot42** [florianfesti/boxes#251]
I'd like to produce boxes, otto-bots and the like by using an endmill. 

When setting the bur correction parameter to 0.0 I get a very loose fit of the parts.
With positive values  fro burn correction as suggested for tighter fit there are additional paths generated at corners which are not needed for milling (in fact they are a pain when generating the gcode).

Is it feasible to introduce an option to disable the burn correction feature for milling?

**Comment by florianfesti** [comment]
Well, technically those additional paths are actually needed to make sure the corners are milled out. 

You can set the burn param to 0.0 and do the kerf correction with another tool. Most CAM software should be able to do that. Not that I have any experience with that.

There is some outdated documentation on this topic at https://florianfesti.github.io/boxes/html/api_burn.html

The new back end now optimizes the path for internal  corners in https://github.com/florianfesti/boxes/blob/master/boxes/drawing.py#L188 replacing back facing arcs by Bezier loops. (Yes, the code is not properly commented and difficult to understand). It would be easy to replace them with something different. What path would you suggest instead?

**Comment by ottobot42** [comment]
I use Estlcam an Fusion360 to generate the gcode. They do have an option to overcut in corners.

When I set the burn param to 0.0 I get a plai path but the resulting pieces fit together very loosely. 
Measuring the fingers of a 3mm Plywood part they are 2.8mm wide and the gaps are 3.2mm wide instead of 3.0mm and 3.0mm as I would prefer. 
I did some other projects with fingerjoints in Fusion360 and those fingers were a snug fit. Thus I suspected that you apply a correction based on the burn parameter. My assumptions might be wrong though.

**Comment by florianfesti** [comment]
The burn parameter is half the width of cut aka cutter radius aka kerf. In Boxes.py the width of the lines show the what is actually cut away (assuming the burn value is correct).

Unless you can do cuts with zero width you need to compensate for the width of the cut somehow. While I am not familiar with Estlcam I am pretty sure you can tell it the diameter of the milling bit somewhere. If you set burn to 0.0 and set your milling bit size correctly everything should just work. Alternatively you can set the burn value to the radius of you bit and tell your CAM software to stay on the lines.

**Comment by ottobot42** [comment]
OK. I think I get the idea: setting burn to 0.0 should produce the exact geometry. So with a material thickness of 3.0mm all fingers and gaps should be of 3.0mm width and height respectively.

I used a 1.0mm drill bit and I rechecked my settings in Estlcam were correct. CAM software is generally taking care to offset the path of the drill bit by half of its diameter. 
 

I did some further tests importing the DXF and SVG into Fusion360 and CorelDraw X6:

In Fusion360 dimensions of the fingers show that SVG output is correct ( horizontal and vertical fingers and gaps are 3.0mm wide). 
![Fusion360-SVG_FingerMeasurements](https://user-images.githubusercontent.com/72408490/95302832-c3485400-0882-11eb-8faa-7a6b24a310e9.png)

DXF (in Fusion 360) is imported as single lines and vertical fingers and gaps are 3.0mm but horizontal fingers are 2.7mm and horizontal gaps are 3.3mm wide. The height of fingers however is 3.0mm for both horizontal and vertical fingers.
![Fusion360-DXF_FingerMeasurements](https://user-images.githubusercontent.com/72408490/95302586-72386000-0882-11eb-8784-432806af685f.png)

- When I import the DXF into CorelDraw X6, I get roughly the same measurements as in Fusion360.
![CRD-DXF_FingerMeasurements](https://user-images.githubusercontent.com/72408490/95302122-cdb61e00-0881-11eb-9ef2-da690b77f3dc.png)

For me it is a bit harder to get exact dimensions there. This might be due to the fact that the individual lines seem to be kind of double layered here. The object properties of a line show that it has been imported as an open curve comprised of 6 nodes and 2 lines.
![CDR-LineProperties](https://user-images.githubusercontent.com/72408490/95302148-d4dd2c00-0881-11eb-94ba-5f9e3d95869f.png)

My usual workflow is to rearrange shapes/objects in CorelDraw before generating drill bit paths and gcode with Estlcam. 
Importing/modifying/exporting DXF with CorelDraw each line is shown as a very slender rectangle in Estlcam. This prevents Estlcam from recognising the outlines as they are not a closed sequence of single lines.

At the end of the day the DXF export from Boxes.py might not be suited as input for milling, unfortunately. So I might have to switch to SVG instead.

Thank you Florian for your time and consideration.

**Comment by Blancanegra** [comment]
Hi, I'm using Corel Draw and SVG format works like a charm. Use 0.0 burn setting for an exact geometry size.
In previous builds, SVG paths were open and I used join curves tool in Corel Draw to close the paths.
In lastest build of boxes.py SVG paths are closed when imported in Corel Draw but in your case I think you must combine the paths of pieces with inner holes, then Estlcam would generate the proper inner and outter tool compensation.

I don't use Estlcam but VCarve, sure there is a toolpath option to mill over the path line. In that case you can use the burn setting  in boxes.py according to your tool radius, simplifying your workflow.

The only thing here, I'm not sure if Corel Draw 6 is managing the SVG files as latest versions would do.

**Comment by ottobot42** [comment]
@Blancanegra: Thanks for your input. 
When I use SVG I need to rescale. That's why I prefer DXF.
But maybe I'm missing something here.

**Comment by florianfesti** [comment]
I hope you found a work flow that is sufficient for you. I currently don't see what else can be done here. So I am closing the ticket.
