### ISSUE TITLE
Generator is not working

### ISSUE THREAD

**Issue by vverdouw** [florianfesti/boxes#255]
Hello everybody,

I used this great box-generator for my lasercutter, a couple of times. What an awesome programme!
Anyway, it seems that the generator is not working today.

the error i get:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /boxes.py/AngledBox.

Reason: Error reading from remote server

Apache/2.4.6 (CentOS) Server at www.festi.info Port 443

thnks!

**Comment by florianfesti** [comment]
Yeah, there was an issue with /var/ on the server running out of space. Deleted a few old docker images. Things should be back to normal. Thanks for reporting!
