### ISSUE TITLE
bug in gears generator

### ISSUE THREAD

**Issue by nialabert** [florianfesti/boxes#260]
Seems to have a bug in the gears generator.
I'm not sure but I think it's a confusion and/or mix between module and pitch.

If you stay with the default setting:
Z = 12 
m =  5

You should have 
Dp  = 60
De = 70

But you can find displayed on the svg:
Pitch radius 1: 9.5mm
Outer diameter 1: 21.6mm

Almost an error of π

**Comment by florianfesti** [comment]
After looking at this I am wondering if one of us confuses diameter an circumference. Surprisingly there is exactly a factor π between them.

**Comment by nialabert** [comment]
mmmhhh why the circumference appear in this discussion? 

modulus of 5, number of teeth of 12 should have a outside diameter of 70mm not 21.6mm.
The gear generated is clearly not with the right size.

Sometime the pitch defined as π·m appear, but it's confusing. You can see that on the French page of wikipedia about gears, but not on the English one.

**Comment by florianfesti** [comment]
OK, looks like the module I derived the code from uses this wrongly. Need to have a look where else this needs to be fixed.

**Comment by nialabert** [comment]
Have a look when the pitch is used. It shouldn't. Thanks

**Comment by florianfesti** [comment]
OK; this took way too long for a one line fix. Last time I got lost in the code somehow.

Anyway, thanks for reporting!
