### ISSUE TITLE
language change box is empty 

### ISSUE THREAD

**Issue by hznupeter** [florianfesti/boxes#263]
I have install boxes on my computer,but I can't change the language at bottom.
how to change the code or setting?
![QQ截图20201210130301](https://user-images.githubusercontent.com/6317759/101723923-4d61a280-3ae8-11eb-9357-b8a7c7a47fa0.png)

**Comment by florianfesti** [comment]
This is probably cause by boxes.py not finding the language files:

```
locale/en/LC_MESSAGES/boxes.py.mo
locale/fr/LC_MESSAGES/boxes.py.mo
locale/zh_CN/LC_MESSAGES/boxes.py.mo
```
How did you install Boxes.py and under which operating system? It's quite possible some variants still miss places those files. May be you can find them some where on disk and I can just add that to the search path.

**Comment by hznupeter** [comment]
i have fix this problem by install on another computer.
i want to help you translate to chinese. but i cant edit on https://translate.zanata.org

**Comment by mahmyd** [comment]
> i have fix this problem by install on another computer.
> i want to help you translate to chinese. but i cant edit on https://translate.zanata.org

You can. Just connect to chinese team before. 
Login to zanata, go to Setting - Languages, click on Join a language team, find language what you need, open it and click on Join Team button 
![image](https://user-images.githubusercontent.com/10675660/105056332-bf7cbe00-5a7c-11eb-9670-224c64ee6d04.png)

**Comment by florianfesti** [comment]
Looks like the original issue is solved. Closing.
