### ISSUE TITLE
Default burn parameter to 0

### ISSUE THREAD

**Issue by Shikoruma** [florianfesti/boxes#265]
Can the the default value of the burn parameter could be 0 ?
It depend on the laser cutter so it is better to be set to 0.

I lost many objects because 0.1 is really to much.

**Comment by florianfesti** [comment]
Sorry, there is just no value that is not wrong for almost everyone. I put 0.1 there instead of 0 so people may pick up that need to put a value there. Sorry, this didn't work for you.
