### ISSUE TITLE
Castle render

### ISSUE THREAD

**Issue by mattyzell** [florianfesti/boxes#266]
I just signed up for GitHub to try to contribute an image (well, a rendering actually).
![Castle render TinkerCAD](https://user-images.githubusercontent.com/76002137/102109685-2c9b9480-3de9-11eb-9fc4-36793dfb6a8d.png)

**Comment by florianfesti** [comment]
Thanks for all the effort. This is a very rudimentary thing I did as a table decoration for a medieval style wedding. I have ever since dreamed of this turning into a proper castle but I never real had the time for that and I really can't make any promises right now.

**Comment by mattyzell** [comment]
I'm not sure if that image was helpful or not.  I'm just starting to tinker
with laser cutting and the related software.
Cheers!
