### ISSUE TITLE
triangles attachment in electronicsbox

### ISSUE THREAD

**Issue by jensvanhoof86** [florianfesti/boxes#269]
Hi,

New user here, made the cardbox a couple days ago without any issuse. Thanks for the superb project!
Today I tried to make an electronicsbox using the browser version. It seems though that the 4 triangles are generated without the fingers, and the walls are not generated with the slots to fit them. 
![ele](https://user-images.githubusercontent.com/69724005/103678085-66dcf980-4f83-11eb-8607-b4405c6691c1.png)

So now I find myself with a nice box and 'clean' triangles but no strong way to attach them. Do I have some settings wrong or is this a bug?

Thanks a lot!

**Comment by florianfesti** [comment]
Unfortunately the finger settings are the same for both the box's edges and these triangles. If you don't want to increase the triangles to fit the fingers you can change the value of `surroundingspaces` in the FingerJoint Settings to `0` or may be `0.5`. Reducing `finger` and `space` to `1` can also help but changes the appearance of the finger joints much more and increases cutting time (but also strength).
