### ISSUE TITLE
Make fingers longer

### ISSUE THREAD

**Issue by rokelvisar** [florianfesti/boxes#270]
It would be great if we could set the finger length adjustment for rendering "longer" fingers. Some of us like to manually make fingers longer - that allows us to sand off the burned edges. 

I suggest adding an input parameter to finger settings. This value would be added to material thickness when rendering fingers.

Example:

- I use material thickness 4mm.
- I don't like black/brown edges, so I input 0.5 to new input
- box fingers are no more 4mm long, but 4.5mm and I am super happy because I can sand this extra 0.5mm down

**Comment by Azzman77** [comment]
This woul be great!

**Comment by StevenHirst** [comment]
Given that most parameters are in terms of material thickness, you could set the 'finger length' to say 1.1 (which would be 4.4mm in your case) if it were implemented in this way.

**Comment by StevenHirst** [comment]
I've thought a bit more about this, and:

I use material that is 3.2mm.
Set material thickness to 4mm
In finger join settings set 'play' to -0.2

This seems to work well for boxes, but not so well for trays (need to close up the gap from 4mm to 3.2mm).

Photo to follow...

**Comment by florianfesti** [comment]
OK, I finally added another parameter to the Finger Joint settings. Last time I tried that I looked at the wrong place and was intimidated on what it would take to make this really work. Turns out there is a much better place.

Thanks to everyone pushing for this. Please test the new `extra_length` setting!
