### ISSUE TITLE
Save to URL button doesn't do anything

### ISSUE THREAD

**Issue by KittyDreadful** [florianfesti/boxes#271]
Hi,

I've tried in Firefox and Edge to create a box and save the file as a SVG.   When I click on the Save to URL button, nothing happens.  It doesn't matter what box I make - nothing happens.

**Comment by florianfesti** [comment]
You need to press `Generate`. For SVG just use "Save page as" in your browser. For other formats your browser should ask you for a location to save right away.
The "Save to URL" button saves the current setting in the URL bar - allowing you to save the link to this exact box.
