### ISSUE TITLE
Zanata pot file update. 

### ISSUE THREAD

**Issue by mahmyd** [florianfesti/boxes#272]
Hi. I want to add a translation for Russian, but can't find some lines in zanata. Could you please push actual boxes.py.mo file, or please grant me editing rights. User **mahmyd** or email kochergin.anatoliy@gmail.com
Thanks.

**Comment by florianfesti** [comment]
Looks like Zanata is more or less dead. I failed to upload or download any files. Updated the .pot file in the repository, though.
