### ISSUE TITLE
il file zip estratto in extension non compare in inkscape

### ISSUE THREAD

**Issue by sylunder** [florianfesti/boxes#273]
Ho estratto il file zip nella cartella extensions di inkscape ma aprendo il programma inkscape l'estensione non compare. Cosa devo fare o cosa sbaglio? Grazie
![Screenshot (28)](https://user-images.githubusercontent.com/60463634/105627558-f0bc0c00-5e37-11eb-95db-194b32b46f33.png)
![Screenshot (29)](https://user-images.githubusercontent.com/60463634/105627576-03cedc00-5e38-11eb-86ae-dd076447573f.png)

**Comment by florianfesti** [comment]
Boxes.py is a Python programm and for the Inkscape extensions to work it needs ot be able to run and Inscape needs to find it.

See https://florianfesti.github.io/boxes/html/install.html and  https://stadtfabrikanten.org/display/IFM/Boxes.py for details.
Also have a look at #314 for Inkscape 1.0 support.
