### ISSUE TITLE
Feature Request: TrayLayout Options, Dispenser Generator

### ISSUE THREAD

**Issue by havocmayhem** [florianfesti/boxes#278]
Would it be possible to make a few enhancements to the 'TrayLayout' Generator

- Add in an option for different kinds of lids and bottoms, similar to 'TypeTray'
- Allow for an angled bottom, with the angle specified by the user. Massive bonus if you can somehow have a variable angle for each sector of the tray. 
- Allow for variable bottom layer heights for each segment.

From a UI perspective, the angles or layer heights can perhaps be input in the following way
![image](https://user-images.githubusercontent.com/44165205/107738899-a2f73d00-6d2d-11eb-91ba-a772fbb8b3a9.png)

The goal is to be able to build things like this:
![image](https://user-images.githubusercontent.com/44165205/107739000-e5b91500-6d2d-11eb-90a5-8905aa0bcf51.png)

Separately, could you maybe work on a 'Tile Dispenser' Generator?
This would make something like this:
![image](https://user-images.githubusercontent.com/44165205/107738937-bb675780-6d2d-11eb-84f6-d326db202260.png)
Customisable parameters here would be the basic dimensions, tile thickness, width of the central gap, etc. Ideally, the bottom plate would be angled slightly upwards towards the front, to prevent the tiles slipping out unless they are pulled manually.
Bonus points if the generator can allow for multiple such dispensers placed side by side, in a single unit.

**Comment by havocmayhem** [comment]
Here's another example of a tray with sloping bottoms. This makes it much easier to remove small tokens.
![image](https://user-images.githubusercontent.com/44165205/107740621-970d7a00-6d31-11eb-82c9-615521da1a0e.png)

**Comment by florianfesti** [comment]
The TrayLayout works differently than TypeTray. As all walls and floors are optional every wall can become an outer wall. So some features are not possible there. This includes different top and bottom styles. Adding those would end up in trays that cannot be assembled.

Having angled floors to allow picking up small parts is interesting but I am not sure if it can be done with TrayLayouts. May be if all floors are angled in the same direction.

**Comment by florianfesti** [comment]
For the Dispenser generator: See https://festi.info/boxes.py/Dispenser?language=en

Be aware that by having requested this new generator you are obligated to do a test cut and to provide a good example picture.

**Comment by havocmayhem** [comment]
Wow, thanks!

I've since moved on to using Onshape to design things from scratch, but I
hope this will be useful for other people starting out.

**Comment by florianfesti** [comment]
See new SmallPartsTray generator (still in Unstable) and #497

**Comment by florianfesti** [comment]
OK, there now is [SmallPartsTray](https://festi.info/boxes.py/SmallPartsTray?language=en) and [SmallPartsTray2](https://festi.info/boxes.py/SmallPartsTray2?language=en). I still have some ideas for TrayLayout but this should be enough for this ticket. Closing.
