### ISSUE TITLE
Feature Request/Idea

### ISSUE THREAD

**Issue by KittyDreadful** [florianfesti/boxes#293]
I was thinking of a way to make an organizer similar to this:
https://www.etsy.com/listing/450995384/triple-slot-mail-organizer-mail-sorter

With the option for the sides to have flex instead of finger joints. 

Something like this:
https://www.etsy.com/listing/918127756/cap-organizer-cap-and-key-organizer-key
The baseball hat doesn't have a bottom to it, which defeats the purpose of the organizer.  

Thoughts?

**Comment by jd-boyd** [comment]
Both Etsy links are broken, FYI.

**Comment by florianfesti** [comment]
This should be solved by the new WallRack generator added with #573.
