### ISSUE TITLE
Default silverware generates self-intersections

### ISSUE THREAD

**Issue by matkoniecz** [florianfesti/boxes#297]
https://festi.info/boxes.py/Silverware?language=en press generate 

Note 
![screen](https://user-images.githubusercontent.com/899988/111366335-a6b31200-8693-11eb-8e41-4863d186a293.png)

**Comment by florianfesti** [comment]
> There are actually quite a few generators that create self-intersections and other quirks on default settings. And it is rather inconvenient when you want to get a general idea of the design without fiddling with the settings.

Please open tickets!

**Comment by florianfesti** [comment]
Yeah, the Silverware generator needs some love. That's not the only issue. It probably needs a top part similar to the RoundedBox. It is one of the oldest generators but hasn't made it out of "Unstable" yet.

**Comment by florianfesti** [comment]
OK, at least the most urgent fixes...
