### ISSUE TITLE
duplicate message definitions in po files

### ISSUE THREAD

**Issue by tinkercnc** [florianfesti/boxes#309]
./setup.py build
running build
running build_py
updatePOT()
generate_mo_files()
po/en.po:3768: duplicate message definition...
po/en.po:727: ...this is the location of the first definition
msgfmt: found 1 fatal error
po/fr.po:3750: duplicate message definition...
po/fr.po:721: ...this is the location of the first definition
msgfmt: found 1 fatal error
po/zh_CN.po:883: duplicate message definition...
po/zh_CN.po:881: ...this is the location of the first definition
msgfmt: found 1 fatal error

Regards

**Comment by florianfesti** [comment]
Took me a little to figure how those duplicates sneaked in. The extraction tools should actually prevent this, but...
