### ISSUE TITLE
SlatWall - 100mm versus 3” distance between slats

### ISSUE THREAD

**Issue by ChrisLaserman** [florianfesti/boxes#312]
Love the slatwall boxes, but a setting to adjust the distance between top hook and bottom hook would be great. It appears to be hard-coded for standard European 100mm slatwall.  And there are no US sources for 100mm, just 3”.  Can you add an adjustable setting for slat distance?  Or hard coded 76.2mm?  I have no python skills.

Or is there a configuration setting that I am missing?
Thanks!

**Comment by florianfesti** [comment]
Yes, these are still a bit rough. Many generators have been only ever used once. It's also possible that the hooks are a bit too tight for some walls. I will need to have a look at them soon anyway as we got a new make of slatwalls in our workshop and I need to redo some of our tool holders.
So try out some smaller pieces before pouring too much laser time and material in your builds.

**Comment by florianfesti** [comment]
Added `hook_depth` in the slat wall settings to make the hooks fit into shallower slits.
