### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Feredyr** [florianfesti/boxes#317]
Hello,
I wanted to share with you what I build thank to your work.
Here Is my first insert for the boardgame "It's a wonderful world"
![IMG_20210506_140735](https://user-images.githubusercontent.com/78080058/117296613-8cb4d500-ae75-11eb-9cc3-87d8af2f3469.jpg)
the dividerTray to store all cards
![IMG_20210506_140904](https://user-images.githubusercontent.com/78080058/117296695-a524ef80-ae75-11eb-8afa-58e7eb4f391f.jpg)
And the small closed boxes for tokens.
![IMG_20210506_141912](https://user-images.githubusercontent.com/78080058/117297156-2d0af980-ae76-11eb-93ad-6e7af4736526.jpg)
Those ones are  3 different closed boxes melt in Inkscape to get the lid  with large fingers and cut edges of the sides.

again Thank you :)

Bye

**Comment by florianfesti** [comment]
Very nice work!

As soon as I get #234 done I need to bug you for the parameters to merge the three boxes/trays into one generator.

**Comment by florianfesti** [comment]
You are welcome! Seeing Boxes.py put to good use like this is what keeps me going.


Still closing this here as I try to keep the ticket list short. You are invited to post this project in a comment on the Hackaday.io project page (https://hackaday.io/project/10649-boxespy) where it is probably much more visible.
