### ISSUE TITLE
Independent X & Y Burn Values (enhancement)

### ISSUE THREAD

**Issue by tiamot** [florianfesti/boxes#320]
I work with a diode laser and the kerf is different in the X and Y depending on thickness of material cut.
It would be a nice feature to allow for setting different burn values for those working with diode lasers.

**Comment by florianfesti** [comment]
I agree that it would be a nice feature. Unfortunately this is very difficult given the way the [kerf correction is implemented in Boxes.py](https://florianfesti.github.io/boxes/html/api_burn.html). So this is unlikely to happen any time soon unless someone has a very clever idea.
For now you are probably best of setting the `burn` value to zero and then use some CAM software that can handle the kerf correction.
