### ISSUE TITLE
Boxes with flex second latch option

### ISSUE THREAD

**Issue by targor** [florianfesti/boxes#322]
It would be awesome if the flex box generator could have an option to add a second latch so you can generate a box that has a double latch opening mechanism at the top of the box. (like this ones: https://www.thingiverse.com/thing:17240)

**Comment by florianfesti** [comment]
https://festi.info/boxes.py/DoubleFlexDoorBox?language=en

Still in Unstable until someone(tm) actually cuts one.

You clearly owe me a nice sample picture to go with the move to the "Boxes with Flex" group.

**Comment by targor** [comment]
Thank you soo much, this is really awesome :) .. i am currently waiting for a new laser module, when it arrives ill make a chest and send you some pictures when it is finished :)

**Comment by targor** [comment]
As promised, here are some pictures of one double latch box. i cutted the svg a little bit because my woodden sheet was too small. There you go :)

![00](https://user-images.githubusercontent.com/7933943/121797532-113b0600-cc21-11eb-9251-549c67c5bdad.jpg)
![01](https://user-images.githubusercontent.com/7933943/121797533-126c3300-cc21-11eb-8dbb-b93ff7b0e705.jpg)
![02](https://user-images.githubusercontent.com/7933943/121797534-1304c980-cc21-11eb-9042-01cb0b92dfd0.jpg)
![03](https://user-images.githubusercontent.com/7933943/121797535-1435f680-cc21-11eb-8c31-f8106c44b30e.jpg)
