### ISSUE TITLE
Get error when create IntegratedHingeBox

### ISSUE THREAD

**Issue by jonathanoeijoeng** [florianfesti/boxes#326]
I got this error when creating IntegratedHingeBox.
I tried to use default value but still get same error.
Could you help me?

An error occurred!
argument --reference: invalid float value: ''

**Comment by jonathanoeijoeng** [comment]
Suddenly it solved by itself

**Comment by florianfesti** [comment]
The issue is actually just what is says: You let the reference setting at the bottom empty. It has do be some number. "0" for no reference rectangle.
