### ISSUE TITLE
Request: Can dispenser generator

### ISSUE THREAD

**Issue by AshaiRey** [florianfesti/boxes#330]
I would like to request a new generator. One to generate a can dispenser at various sizes.
The size would depend on the can size and the number of cans it would hold in 2 layers.
And example of a can dispenser can be seen here 
https://d2t1xqejof9utc.cloudfront.net/screenshots/pics/04c43617455bef35938629dcf7d501da/large.JPG

**Comment by florianfesti** [comment]
43bd7d12d318e353cc1178f714701a23ef6ed989 implements this. This is the result of #401

https://festi.info/boxes.py/CanStorage?language=en in the Misc category
You have to thank @SuksAE for the huge amount of work he put into this.
