### ISSUE TITLE
Picture for silverware caddy

### ISSUE THREAD

**Issue by Suezyque** [florianfesti/boxes#334]
Picture for silverware caddy. Caddy does not fit together as generated. Instead of finger holes at the bottom of the longest piece there needs to be tabs instead.
![205D8E8A-6BC9-43F4-8374-AF6C1B59B4FD](https://user-images.githubusercontent.com/91911306/135903609-0fa5e387-7927-42d4-a67b-3612b05faa8d.jpeg)
![D3C8944E-69BD-4271-9D04-112334FCDA05](https://user-images.githubusercontent.com/91911306/135903626-e946bed2-1b09-460d-970c-6ae95936ee84.jpeg)
![AB8F395B-3040-49D5-9580-E030876A93FE](https://user-images.githubusercontent.com/91911306/135903633-1bb3a01a-4766-46e2-8f36-45d88bfe2374.jpeg)

**Comment by florianfesti** [comment]
This ticket fell through the cracks somehow. Thanks a lot for these very nice pictures. Added one as a sample image.
