### ISSUE TITLE
Typetray has wrong front wall when back_height is defined

### ISSUE THREAD

**Issue by RestlessRabbits** [florianfesti/boxes#336]
![grafik](https://user-images.githubusercontent.com/28935071/140313876-57f8e4fb-e44f-4c18-be3c-c73f3a1a1fff.png)
Box with back height 50 - the joints are moved but the front-wall part is not changed accordingly.
![grafik](https://user-images.githubusercontent.com/28935071/140313999-ee325ad7-49b1-42f9-9c81-beadc4fd2d6b.png)
Same configuration but with back_height 0 - here it would fit - since it seems to be the dafault type for the front.

**Comment by florianfesti** [comment]
Yeah, I need to go back to actually cut stuff at least once before pushing it...
I already have a (tested!) fix for that but forgot to push it. I will get it online as soon as I get back to my hacker space. May be a few days, though.
