### ISSUE TITLE
The size of the drill hole on the drillbox seems to be wrong?

### ISSUE THREAD

**Issue by KittyDreadful** [florianfesti/boxes#338]
I recently created a drillbox file with the following values:
sx: 25X6
sy: 25x7
h: 70
first hole: 11
hole increment 0 <<  I wanted all of the holes to be the same.

When I saved the file and imported it as a SVG to cut, the 11mm hole was now 20mm.  I checked the sizes of the other cuts, like the thickness of the material, and that remained at 3mm, so its not like the file was expanded.  I just don't think its rendering correcting. 

Also, I'd like to make a suggestion for this box. There are two layers of holes, it would be great if the top layer height could be adjustable.  It appears to be a hard value and is rather lower.   I'm using this to create stands for my pens and I need them to be deeper.

Thanks alot!

Katrina

**Comment by florianfesti** [comment]
Ok, added a few updates to the DrillBox including fully adjustable layers. Note that it moved to the "Trays and Drawer Inserts" group.
