### ISSUE TITLE
tote box with centre handle

### ISSUE THREAD

**Issue by Azzman77** [florianfesti/boxes#344]
Forgive me if I am missing it or if its already been raised, but is there a generator for a multi compartment open top box with the ability to add a centre partition the extends up with a handle? I know this option is available with this on the back of the box but not the middle. cheers
![20211124_120136](https://user-images.githubusercontent.com/40506978/143142630-eb94e763-49cd-403a-8671-9eddabc8dd42.jpg)

**Comment by florianfesti** [comment]
No, there currently is no generator to do this. After thinking a bit about it I don't think I will add one. There are just too many possible variants to get this nicely into the UI. Just use TypeTray or TrayLayout and modify the piece(s) you want handles on with Inkscape or any other vector graphics program.

**Comment by Azzman77** [comment]
I would think it's an option that would be more popular than having this
exact option for the back. And simpler because the sides wouldn't change at
all.
