### ISSUE TITLE
Keypad parts overlapping

### ISSUE THREAD

**Issue by gcollic** [florianfesti/boxes#346]
Hello 👋

I noticed that the keypad triangle parts are overlapping (with default settings).

![image](https://user-images.githubusercontent.com/763200/143690249-787f9c7b-66bb-4073-a59e-2497295bb57e.png)

The code generating them is:

``` python
        self.rectangularTriangle(
            tr, tr, "ffe", num=4,
            callback=[None, lambda: self.hole(trh, trh, d=d1)]
        )
```

https://github.com/florianfesti/boxes/blob/master/boxes/generators/keypad.py#L92-L95

**Comment by Jikstra** [comment]
Same for the electronicsbox, seems that the rectangularTriangle method with the edges argument "ffe" is causing the problem.

**Comment by florianfesti** [comment]
Yeah, no idea how I messed that up.
