### ISSUE TITLE
BinTray middle 'floor' is misplaced when sy has different widths

### ISSUE THREAD

**Issue by Al0rin** [florianfesti/boxes#348]
[For example 80:20](https://festi.info/boxes.py/BinTray?FingerJoint_angle=90.0&FingerJoint_style=rectangular&FingerJoint_surroundingspaces=0.5&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&sx=50&sy=80%3A20&h=50&outside=0&outside=1&front=0.4&thickness=1.5&format=svg&tabs=0.0&debug=0&labels=0&labels=1&reference=0&burn=0.1&render=1):

I think the middle floor should rather be placed to the indicated (red) position:
![misplaced wall](https://user-images.githubusercontent.com/49208863/144710487-8c7642ed-d83f-49d8-9999-9550c8b8788b.png)

Am I right? If not just close the ticket

**Comment by Al0rin** [comment]
This is what the model looks like when modified: ![](https://user-images.githubusercontent.com/49208863/144718762-2cd0cc39-a34a-4def-87d9-3ccfd724617d.png)

**Comment by florianfesti** [comment]
Yes, this is obviously wrong. It is surprisingly difficult to come up with test cases that are not symmetrical in any direction...
