### ISSUE TITLE
Help with a plans from boxes.py

### ISSUE THREAD

**Issue by Kukinac** [florianfesti/boxes#367]
Hello,
I hope it is okay I ask for help here - I didn't find a better place for it.

I would like to create boxes on this website, but every time I download the plan, when I put it in my program, I can see that the plan has some "extra line loops" in the joint corners (only on the inside corners). Very small, I have to zoom in or look very carefully.
I guess it is for the joints to fit well?

I have a problem with this. I don't want it there, because it does not help me with anything, it leaves a small dots (after cutting) in the corners and it is not pretty.

Does anybody know what can I do about it? How can I get rid of it? 
Please, I am desperate :) hah
Thank you!

**Comment by florianfesti** [comment]
See https://florianfesti.github.io/boxes/html/faq.html#why-are-there-tiny-weird-loops-in-the-corners and https://florianfesti.github.io/boxes/html/faq.html#i-really-don-t-want-those-weird-tiny-loops
