### ISSUE TITLE
www.festi.info/boxes.py/ - 502 Proxy error

### ISSUE THREAD

**Issue by martinohanlon** [florianfesti/boxes#383]
https://www.festi.info/boxes.py/ is returning the following error.

```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request [GET /boxes.py/](https://www.festi.info/boxes.py/).

Reason: Error reading from remote server

Apache/2.4.6 (CentOS) Server at www.festi.info Port 443
```

I tried from multiple connections, it appears to be more than a local connection issue.

![image](https://user-images.githubusercontent.com/2329501/162766468-88ac4262-a768-45cc-8538-5a832ebec7dc.png)

**Comment by florianfesti** [comment]
Thanks for reporting! Looks like docker needed a bit of encouragement and restarting. Let's hope it keeps running.
