### ISSUE TITLE
Labels translate

### ISSUE THREAD

**Issue by HaSHsss** [florianfesti/boxes#397]
I want to add translation for svg Tags/Labels. I know that have to use `gettext` and everything related with it.

I'm couldn't decide. Which variable is best  to manipulate?

Maybe here? 
`/boxes/__init__.py`
```
            if self.labels and label:
                self.text(label, x/2, y/2, align="middle center", color=Color.ANNOTATIONS, fontsize=4)
            self.ctx.stroke() 
```

**Comment by florianfesti** [comment]
Well, the issue is not so much translating the labels but collecting the labels for translation. The best way to do that would be wrapping all label texts in `_( )`.

**Comment by HaSHsss** [comment]
The problem I am facing
the fact that the parameter with the language is not passed to the generator.
Can you add this piece of code?

**Comment by florianfesti** [comment]
Yeah, I noticed. I started a patch a while ago but there are still a few pieces missing. I'll try to get that finished.

**Comment by florianfesti** [comment]
Ok, this obviously failed. That's kinda embarrassing...

Anyway, here is the - actually pretty small - solution: ea1ac786d5ea187aa8ac9bd920a92696dcc4e656 and 9a9499e4054f10e9ce65ea83275c53dce150c776 as an example how to use that.
