### ISSUE TITLE
inner_corners style as corner in U - Edge with cabinet hinges

### ISSUE THREAD

**Issue by HaSHsss** [florianfesti/boxes#404]
Do not consider me a bore please )))
There is little issue with style of `inner corners`
If selected **`inner_corners`** style as **`corner`** in `U - Edge with cabinet hinges` 2 corners still left `loop` style
![U edge](https://user-images.githubusercontent.com/63124812/172200493-79ad24b3-e783-4f7f-8bf5-f1e2ae46fcd8.JPG)

noticed in `AllEdges `generator

**Comment by HaSHsss** [comment]
What is this `loop `angle used for?
For milling machine?

**Comment by florianfesti** [comment]
Luckily someone(tm) wrote a page about this: https://florianfesti.github.io/boxes/html/api_burn.html

While these are loops but they have a different reason: I used a 270° corner (made from 180 and 90°) as that simplified the code and I am lazy. Fixed now.
