### ISSUE TITLE
DrillStand generator not working

### ISSUE THREAD

**Issue by rogersbarn** [florianfesti/boxes#405]
The DrillStand generator creates below error even with the default settings.
---------------------------
This page contains the following errors:
error on line 16 at column 3: Double hyphen within comment: <!--
DrillStand - Box for drills with each compartment
Below is a rendering of the page up to the first error.
----------------------------

**Comment by florianfesti** [comment]
Ooops. I already fixed that in e6ef17c07071cc4eda138726101d6c8d1c9493d8 but did not update the web instance in a while. Let's hope everything still runs smoothly as I did quite a few changes since...
