### ISSUE TITLE
platonic 20 sides 100mm

### ISSUE THREAD

**Issue by YodaMaster18** [florianfesti/boxes#409]
![platonic_20_1](https://user-images.githubusercontent.com/108149589/175644894-5fac33ab-5d8a-40d0-8f0a-995dd151456a.jpg)

Is this working, I have really no idea :-)

**Comment by florianfesti** [comment]
This is working but doesn't show the whole piece. Not sure if this is an issue with posting or the picture was like that from the beginning. May be try a picture from further away. I can cut it to size later.

**Comment by YodaMaster18** [comment]
![20_vlak_Github](https://user-images.githubusercontent.com/108149589/175801414-01d55eab-8da6-40d3-abd0-6195141703ba.jpg)

I think this is better, thnx

**Comment by florianfesti** [comment]
Thanks for the extra effort. I will not update the web instance right away but the image will show up as soon as I will.

**Comment by YodaMaster18** [comment]
Thank you!Vriendelijke groeten,Jochem Douwes Van Blommesteinstraat 22614 ER Delft 06-28411405
-------- Oorspronkelijk bericht --------Van: Florian Festi ***@***.***> Datum: 26-06-22  16:49  (GMT+01:00) Aan: florianfesti/boxes ***@***.***> Cc: YodaMaster18 ***@***.***>, Author ***@***.***> Onderwerp: Re: [florianfesti/boxes] platonic 20 sides 100mm (Issue #409) 
Thanks for the extra effort. I will not update the web instance right away but the image will show up as soon as I will.
