### ISSUE TITLE
Upload Box Pictures

### ISSUE THREAD

**Issue by KaKah1** [florianfesti/boxes#415]
How do I upload pictures of example boxes with missing pictures?

**Comment by florianfesti** [comment]
You can just click on the " Attach files by dragging & dropping, selecting or pasting them. " below the comment box below. Either here in this ticket or in #140

The [contributing page](https://florianfesti.github.io/boxes/html/CONTRIBUTING.html#provide-photos-for-generators) has a bit longer description for people that want to submit the picture as a pull request. But this is a bit more involved and not necessary. I am happy to add the picture myslef if you just attach it to any ticket.
