### ISSUE TITLE
Drillbox Generator improvement

### ISSUE THREAD

**Issue by lost-hope** [florianfesti/boxes#416]
Hello, 
first of all great project overall. used it on my private laser cutter and when we got one in the company i pulled it up in front of the sales guy, and he was in awe. 

I wanted to make a drillbox for some drills (obviously)  and saw that you can enable the stagable edge for the bottom.

is it possible to have that option for the top edge as well? that way i could have multiple boxes of the same size and stack them to safe some space when not needed
Generator URL:
https://festi.info/boxes.py/DrillBox?language=en

**Comment by florianfesti** [comment]
Yes, this is one of the older box generators that do not yet have some of the improvements of some of the more modern ones.

**Comment by lost-hope** [comment]
Thanks.
I will upload a photo once i have cut and assembled it
