### ISSUE TITLE
Planetary2 Issue

### ISSUE THREAD

**Issue by lost-hope** [florianfesti/boxes#417]
in the Generator for the Balanced force Difference Planetary Gear (https://festi.info/boxes.py/Planetary2?language=en) seems to be an issue where the holes seem misplaced with the default settings: 
![image](https://user-images.githubusercontent.com/6001498/181179162-a71abb40-4ec2-4302-af67-74ea7b90a474.png)
![image](https://user-images.githubusercontent.com/6001498/181179103-08672ec9-3299-47af-bfd6-5263af23fcc2.png)
![image](https://user-images.githubusercontent.com/6001498/181179022-408a4c09-e9fb-430e-a432-2d8ecc550c01.png)
![image](https://user-images.githubusercontent.com/6001498/181178617-6cf5c206-d8b3-4285-90bb-a7dbeb5e58d0.png)

**Comment by florianfesti** [comment]
Well, this thing should probably be in the Unstable group. I doubt this is the only issue...

**Comment by florianfesti** [comment]
Oh, I fixed the modus handling at some point. So the default is a bit large now. If you lower the modulus to 1or 1.5 the spokes are gone.

**Comment by florianfesti** [comment]
OK, I moved the generator to "Unstable". This needs more work to get really working. And I currently don't have the time for that. I may get back to it later or some one else can pick this up.
