### ISSUE TITLE
Inside fingerjoint corners have incorrect rounding

### ISSUE THREAD

**Issue by JelleB** [florianfesti/boxes#42]
it seems the corners of fingejoints are rounded, which makes assembly slightly easier. However, the inside corners of slots also have what looks like an attempt at rounding that failed: the lines cross and then a rounding is applied at the opposite quadrant of the cross. 
To reproduce: make a closed box (probably applies to all fingerjoints?) [http://www.festi.info/boxes.py/ClosedBox?FingerJoint_angle=90.0&FingerJoint_surroundingspaces=2.0&FingerJoint_edge_width=1.0&FingerJoint_finger=2.0&FingerJoint_play=0.0&FingerJoint_space=2.0&FingerJoint_width=1.0&y=100.0&x=100.0&outside=0&outside=1&h=100.0&thickness=3.0&format=svg&debug=0&reference=100&burn=0.1&render=1](url)
download either as svg or ps file and open in coreldraw (other vector software should work too?) 
switch to 800 or 1600x zoom and wireframe view. 
look at inside corners and wonder how that got there?

I suspect there is a function somewhere that tries to round over corners of edges and fails half the time? The code to make a fingerjoint does not seem to contain such function. 

The rounding is very small, so in practice it does not do much, except make the lasercutter stutter a little in each inside corner, which does result in slightly better fitting slots (unintensionally?)

**Comment by florianfesti** [comment]
The current result indeed is intentional. It is kinda explained in https://github.com/florianfesti/boxes/blob/master/documentation/presentation.odp slides 34 onward.
To make a long story short: The fingers are not rounded. The artefacts you see are an effect of the kerf correction. Yes, it is not beautiful but it works and was easy to implement.
