### ISSUE TITLE
Request - Bread box

### ISSUE THREAD

**Issue by mauroinagoki** [florianfesti/boxes#431]
hi,

I would like to have a breadbox generator that is similar to your shutterbox

![image](https://user-images.githubusercontent.com/379786/189464418-59ac6c02-d40b-4fc8-8e35-4d109b991dc3.png)

Source: https://vectezia.com/laser-cut-living-hinge-bread-box-with-sliding-lid-vector-cdr-file/

**Comment by florianfesti** [comment]
The first version is available in the Unstable category.

By requesting this new generator you agreed to test cut it until it works properly (which is probably won't right away) and to provide a nice sample photo once it does.

https://festi.info/boxes.py/BreadBox?language=en

**Comment by florianfesti** [comment]
Please only cut this very small until it is verified that everything fits together.

**Comment by florianfesti** [comment]
Did everything fit? Do you have a picture?
