### ISSUE TITLE
Request: SlatWallEdges with more configurability

### ISSUE THREAD

**Issue by jan-eckhoff** [florianfesti/boxes#434]
I have a board game table with a rail system that is functionally working like a slatwall, but has other measurements.

Specifically, I need to adjust the vertical height of the hook (right now, it just slides out because it's too small), and although it seems to be fine with my table, it would be nice to set the horizontal distance between the inner edge of the hook and the back of the box.

**Comment by florianfesti** [comment]
Any suggestion for the parameter name? Some idiot has used `hook_depth` for something else already...

**Comment by jan-eckhoff** [comment]
Hi & wow that was fast :-D
I would have looked for something like hook_height for the first parameter, and maybe hook_distance or something like that for the second one.

**Comment by florianfesti** [comment]
You are lucky. I really don't want to start a 3rd page of open issues.

**Comment by jan-eckhoff** [comment]
Thanks! I‘m quite new to GitLab, so maybe I missed it, but did you also implement the hook_height parameter?
Also, will this deploy to the web interface at some point, or would I have to use the script directly to use those parameters?

**Comment by florianfesti** [comment]
Yeah, I closed this a bit too early. Kids, don't drink and push...

Anyway, added more parameter and updated the web instance.
