### ISSUE TITLE
Possible bug in Keypad generation

### ISSUE THREAD

**Issue by kunzeus** [florianfesti/boxes#435]
Hello,

Foremost, I really like the project and what you are doing.
However, we noticed something odd in the generation of the keypad. 
The keypad design is expecting two plates of material to hold the keys.
Now by looking at the frame where you anchor the two plates with the keys we noticed the hight of the fingers is not fitting correctly:
3 mm material thickness in the config leads to a finger hight in the .svg of approximately 5mm? shouldn't that be at least 6?
4 mm material thickness -> ~6 mm finger hight in the .svg?
10 mm material thickness -> ~12 mm finger hight in the .svg?

So, if have 10 mm thick material, the second plate would be loose? That does not seam right to me.
It's also possible that I'm using the tool wrong, but it seems more like a bug to me.
We use the website for the SVG generation, since we use in workshops with non-tech savvy people.

Thank you and keep up the good work.

I add the .svgs here
![fingers](https://user-images.githubusercontent.com/92863097/191010141-a93bd6fc-6419-4064-ad39-0f6a85853666.jpg)
![Keypad 3mm material](https://user-images.githubusercontent.com/92863097/191010387-3390874f-ec8b-4d16-adce-538712ffa32d.svg)
![Keypad 5mm](https://user-images.githubusercontent.com/92863097/191010395-78f6cb2c-ceff-468e-832c-8bd9d278e63d.svg)
![Keypad 10mm](https://user-images.githubusercontent.com/92863097/191010396-276b7a8b-edac-4cec-a39e-9146c4a71b38.svg)
![Keypad 4mm material](https://user-images.githubusercontent.com/92863097/191010398-1ae970fb-beb3-4a0d-ab39-b7d8f9deda7f.svg)

**Comment by gcollic** [comment]
Hello,

The layer where the switches clips on should be around 1.5mm or less (that's how cherry MX compatible swiches are designed). That's why there is a `top1_thickness` parameter on this box, which by default has a value of 1.5mm.

3 mm main material thickness + 1.5 for the switch layer -> 4.5
4 mm -> 5.5
10 mm material thickness -> 11.5

If you only have a single material of 3mm, you can change the `top1_thickness` parameter to this value. The switch won't clip on, but hot glue is perfect for this case :-)

**Comment by gcollic** [comment]
An example of hot glueing them if you use material to thick to clip on:
![image](https://user-images.githubusercontent.com/763200/191093803-a9544332-b884-4dba-bad8-5af74e637f03.png)

You don't have to glue everything, you just need to hit the small holes. It will keep them in place, and is not to hard to remove with a cutter if you really need to replace one someday.

**Comment by florianfesti** [comment]
May be someone(tm) can write a long description (goes to the bottom of the settings page) pointing this out. Just adding it here is fine. I can add it to the generator for you.

**Comment by florianfesti** [comment]
As we are at the topic of improving the UI: Can one of you provide a nice sample photo? May be with less visible hot glue and a better angle?
