### ISSUE TITLE
Divider tray - Open shapes plus enhancement

### ISSUE THREAD

**Issue by leyton01** [florianfesti/boxes#438]
Generating using the default setting for the divider tray and importing into Lightburn shows some of the dividers not joined in the bottom left corner (open shape).
![2022-10-01 14_29_33-_untitled_ _ - LightBurn 1 2 01](https://user-images.githubusercontent.com/20473934/193392648-d8f8a929-4163-4f76-b704-54c84a65b871.png)

Also wondering if having a dividers with half tabs (vertically) rather than half tabs (horizontally) would be a good option.  These could be placed next to each other easily as long as the dividers face the same direction.  See rendered example.
![2022-10-01 14_29_52-_untitled_ _ - LightBurn 1 2 01](https://user-images.githubusercontent.com/20473934/193392646-e8439134-1c13-497f-8cd3-34b9e2fa8632.png)

Thanks for all the good work!

**Comment by florianfesti** [comment]
Please try out the new divider type and close this ticket if everything is OK!

**Comment by florianfesti** [comment]
Guess I waited enough for feedback...
