### ISSUE TITLE
pictures HingeBox

### ISSUE THREAD

**Issue by YodaMaster18** [florianfesti/boxes#442]
Dear Forian,

Hereby my pictures of a HingeBox.LxHxD=300x120x200mm outside

![20221005_203403](https://user-images.githubusercontent.com/108149589/194142937-94784b0d-5a3b-44ba-846b-c12137f31789.jpg)
![20221005_203352](https://user-images.githubusercontent.com/108149589/194142980-f5b0c710-c418-4627-bbdd-0479a5332c93.jpg)
![IMG-20221005-WA0009](https://user-images.githubusercontent.com/108149589/194143127-1aad25c7-6aca-4fe1-9ea7-d38753f5f267.jpeg)
![IMG-20221005-WA0007](https://user-images.githubusercontent.com/108149589/194143242-58d95d4a-5381-4625-b6d6-5ac1794c706c.jpeg)

**Comment by florianfesti** [comment]
Ehm, the hinges go on the inside to allow the lid to open completely - as shown in the image. I'll add a sentence or two of assembly instructions...

**Comment by florianfesti** [comment]
Sorry, I didn't quite get that is is meant to be a bug report. Otherwise I might have answered a bit quicker...
