### ISSUE TITLE
Pictures NotesHolder

### ISSUE THREAD

**Issue by YodaMaster18** [florianfesti/boxes#443]
![20221005_203250](https://user-images.githubusercontent.com/108149589/194143664-f1c22dd1-d4d7-4033-88ab-b95d3131aba0.jpg)
![20221005_203227](https://user-images.githubusercontent.com/108149589/194143795-9cdd4688-e4ca-4aa2-9e47-cf4c52d14034.jpg)
![20221005_211837](https://user-images.githubusercontent.com/108149589/194144824-be455bb2-6e1e-4282-a68a-bb80d56023eb.jpg)

**Comment by florianfesti** [comment]
Thanks for the images
