### ISSUE TITLE
Build / host instructions?

### ISSUE THREAD

**Issue by schvenk** [florianfesti/boxes#445]
This is great! Any chance of some quick instructions (particularly for those of us with limited Python knowledge) for how to self-host the web version and/or build the Inkscape version? Thanks!!

**Comment by schvenk** [comment]
Ah! Found the Inkscape instructions. I'd still love to know how to host my own version of the website at https://www.festi.info/boxes.py/ though.

**Comment by Ranthalion** [comment]
Do these instructions solve your issue?
https://florianfesti.github.io/boxes/html/install/windows.html#native

**Comment by schvenk** [comment]
Yes, that works! I'm on Mac rather than Windows but the WSL instructions work perfectly.

**Comment by Ranthalion** [comment]
There are also Mac instructions at https://florianfesti.github.io/boxes/html/install/macos.html
If this has solved the issue, would you mind Closing the issue here in github?
