### ISSUE TITLE
Problem with hinge boxed lid 

### ISSUE THREAD

**Issue by dpmarkman** [florianfesti/boxes#45]
When I run "http://www.festi.info/boxes.py/IntegratedHingeBox" I get the incorrect line on the box lid shown in the image below.

![image](https://user-images.githubusercontent.com/15081314/31588962-43757de4-b1ae-11e7-9304-23b214cc5233.png)

Here were the settings for the box:

http://www.festi.info/boxes.py/IntegratedHingeBox?FingerJoint_angle=90.0&FingerJoint_surroundingspaces=2.0&FingerJoint_edge_width=2.0&FingerJoint_finger=1.0&FingerJoint_play=0.1&FingerJoint_space=1.0&FingerJoint_width=0.50&ChestHinge_hinge_strength=1.0&ChestHinge_pin_height=2.0&y=100.0&x=100.0&outside=0&outside=1&h=60.0&lidheight=40&thickness=5.31&format=svg&debug=0&reference=100&burn=0.08&render=1

**Comment by florianfesti** [comment]
Yeah, this was a bit lazy solution cutting the ply of the hinge out of the space above. I hope I didn't make it worse...
