### ISSUE TITLE
markdown installed by get error "No module named markdown" when running boxesserver

### ISSUE THREAD

**Issue by decon89** [florianfesti/boxes#454]
When I try to run the boxesserver.py script I get the following error:

>  File "C:\Users\xxxx\Downloads\boxes-master\scripts\boxesserver", line 27, in <module>
>     import markdown
> ModuleNotFoundError: No module named 'markdown'

I expected this to work as I have installed markdown:

> pip install Markdown
> Requirement already satisfied: Markdown in c:\users\xxxx\appdata\local\programs\python\python311\lib\site-packages (3.4.1)

Is this a fault on my end or with the script? And how might I fix this?

**Comment by florianfesti** [comment]
This may be an issue with multiple Pyhton installations. One having markdown installed and one running boxes.py. Try executing it with `python boxes` to use the python version in your path.

**Comment by florianfesti** [comment]
I hope this fixed your issue! Closing.
