### ISSUE TITLE
polygonWall not starting from last point

### ISSUE THREAD

**Issue by Ranthalion** [florianfesti/boxes#458]
**Describe the bug**
polygonWall seems to start a line at the wrong location when creating a polygon with 5 sides.

**To Reproduce**
Pull PR #457 and create a display shelf with slope_top selected.   
![image](https://user-images.githubusercontent.com/1632746/204335537-fa3be925-133c-49c7-9dba-856d32cf5b28.png)

In my case, the calculated borders array evaluates as follows.
```
borders = [215.0, 90, 35.355, 45.0, 254.056, -135, -38.348, -90, 215.0, 90]
self.polygonWall(borders, edge='e', move="up")

```
**Expected behavior**
Each line should begin where the previous line ends.

**Screenshots or Drawings**
This screenshot shows the lines not starting where the previous ends.  This screenshot was created without the callback to add finger holes, but the issue is consistent regardless of callback.
![image](https://user-images.githubusercontent.com/1632746/204316738-e6afd02f-b98a-4418-ad7d-34acadd5ce50.png)

Also, there seems to be an unexpected nub here.
![image](https://user-images.githubusercontent.com/1632746/204316944-b88525b3-e7c7-44de-b715-48614cdabb36.png)

**Additional context**
This bug was discovered while attempting to add additional parameters to display shelf for including a back panel and sloping the side walls at the top.

**Comment by Ranthalion** [comment]
Upon closer inspection, I found that the "nub" is actually a little arc.
![image](https://user-images.githubusercontent.com/1632746/204364178-1ddd937b-89d4-429a-a7d9-3417b5c60c28.png)

**Comment by florianfesti** [comment]
See https://florianfesti.github.io/boxes/html/api_burn.html

**Comment by Ranthalion** [comment]
Burn Correction does seem to be related.  Changing it to 0 gave better results.  
I've also change from negative angles to only use positive angles.  That has gotten me closer to an answer.  My polygon isn't closed, but that may be due to rounding errors.  I'll continue with my implementation and close this issue (and draft PR) if these turn out to be the root causes of my issues.

**Comment by Ranthalion** [comment]
Confirmed that root cause was a negative segment length.  Closing.
