### ISSUE TITLE
DisplayShelf Enhancement: Slope the top and include back panel

### ISSUE THREAD

**Issue by Ranthalion** [florianfesti/boxes#464]
I would like DisplayShelf to be enhanced with a few new options.
1. ~~Include holes to run a power cord~~
2. Cut the top of the side walls based on the shelf angle.
3. Create a back wall

<img src="https://user-images.githubusercontent.com/1632746/205498953-e76d4dbe-f64b-4197-9fab-6a01b9b4532a.jpg" width="300">

**Comment by Ranthalion** [comment]
I've started implementation for this feature by adding a few new parameters.
![image](https://user-images.githubusercontent.com/1632746/205986345-179ab3d5-2cae-4b9a-9e93-546d604cdbb7.png)

**Comment by florianfesti** [comment]
Details like holes for cords should not be part of the generator. Just add them "by hand" in either a vector graphics program like Inkscape or the software controlling the laser cutter.

The other two features make a lot more sense.

**Comment by florianfesti** [comment]
As I see these neat French cleats in the background: Are you interested in testing some of the "Wallmounted" generators with the new French cleat feature?

**Comment by Ranthalion** [comment]
> As I see these neat French cleats in the background: Are you interested in testing some of the "Wallmounted" generators with the new French cleat feature?

I'm willing to help with some of these, just let me know or tag me in an issue.

On the other hand, some of my other personal prioritized ideas are:
1. Automated regression/snapshot test on generators with default parameters
2. Investigate python to WASM to reduce server resources and generate previews in real time
3. Validation/Sanity check messages (For example, overall height of 100mm, but a shelf height of 200mm)
4. New generator - bent acrylic easel stand. Similar to 
<img src="https://user-images.githubusercontent.com/1632746/206024050-acf5c866-f5d8-4a8b-9c1f-fb374cf5a506.png" width=300>
