### ISSUE TITLE
Description for generators

### ISSUE THREAD

**Issue by DanielaFesti** [florianfesti/boxes#48]
It would be cool if the generators could have descriptions (longer than just the one liner in the __doc__ string).

The descriptions could contain information for assembling the generated box, or lists of materials when the thing you build contains more than just the generated walls.

For nicer formatting, a markup language would be good like Markdown (as used by github). Maybe this package would work? -- https://pypi.python.org/pypi/Markups

If projects get more complex, they often get their own homepage somewhere else, e.g., on hackaday.com. Hence, they also should get an (optional) URL that links to more details.

**Comment by florianfesti** [comment]
New code uses the markdown library.
