### ISSUE TITLE
QR Code generator for easy reproducibility

### ISSUE THREAD

**Issue by ccrome** [florianfesti/boxes#490]
**Is your feature request related to a problem? Please describe.**
My problem is that I'm super un-organized, and can't seem to manage to keep the exact parameters for everything I generate with Boxes.  Having the URL embedded as text in the lbrn2 file is nice, but I really want it etched into the product, or at least on a label.  

**Describe the solution you'd like**
I've included a [PR](https://github.com/florianfesti/boxes/pull/488) which does exactly this.  It generates a QR code and embeds it into the lbrn2 file.  This lets me engrave a QR code directly into the product, so I don't have to think about it again.

I'm happy to add svg support to, if there's any interest in this feature. 

![qrcode](https://user-images.githubusercontent.com/286973/211093320-a49b3301-ac77-4ee4-82f4-e28393a0be6f.jpg)

**Comment by florianfesti** [comment]
Fixed with #488
