### ISSUE TITLE
Dogbones holes for milling

### ISSUE THREAD

**Issue by spiffcow** [florianfesti/boxes#51]
I really like your idea, but would want to use it for milling.  Is there any reason this would be difficult?  I'm considering implementing this myself if not.

**Comment by florianfesti** [comment]
Be aware that the way Boxes.py does inner corners is not ideal for milling. It is described on slides 34 to 36 in 
https://github.com/florianfesti/boxes/blob/master/documentation/presentation.odp
It might be OK for small diameter bits.

**Comment by spiffcow** [comment]
The math for a bit radius is pretty easy...  IIRC it ends up being a hole at each corner offset by (sqrt(2)-1)*r, where r is the radius of the bit.  I'll play with it and submit a PR if it works out

**Comment by florianfesti** [comment]
The problem is not adding the hole but removing the overreach. If you can find an easy was of fixing it - even better.
