### ISSUE TITLE
Export to PDF or DXF

### ISSUE THREAD

**Issue by Lt-Lemming** [florianfesti/boxes#52]
Most of the software I've seen for working with laser cutters doesn't support SVG or PS...

Would really appreciate if you could implement DXF or PDF as an output option as theres no good path to go from SVG to DXF that I've been able to find.

**Comment by florianfesti** [comment]
Boxes.py already supports creating both DXF and PS. But you need to install the ps2edit utility (which is currently not installed on the server hosting the online generator).

As an alternative you can use Inkscape to convert from SVG to DXF.

**Comment by florianfesti** [comment]
I was typing too fast. It supports SVG and PS without anything but AI, DXF, gcode,  PLT and PDF with the ps2edit utility.
As cairo supports PDF as an output format I could add pdf as an default output format. But right now there is no way to crop the result to a sane size.
