### ISSUE TITLE
Memory overflow

### ISSUE THREAD

**Issue by HaSHsss** [florianfesti/boxes#532]
**Describe the bug**
If you enter a very large number in the parameters, then the script, trying to generate the layout, overflows the memory and the server CPU

**To Reproduce**
Run This URL with large values in 5-10 tabs in parallel

**Expected behavior**
Need to limit the number of characters on the server side. Also need to take care to the characters after the dot

**Screenshots or Drawings**
![image](https://user-images.githubusercontent.com/63124812/216808453-d5ea13d2-ca67-448d-9be8-293471e104e7.png)

![image](https://user-images.githubusercontent.com/63124812/216808628-72694be7-78f5-406c-82f6-7648c03c0fd0.png)

https://www.festi.info/boxes.py/ is DOWN NOW.
I am sorry

**Comment by florianfesti** [comment]
Deleted link as it randomly creates 100% CPU processes on the server.

**Comment by HaSHsss** [comment]
**I will not give examples.**
I can enter a command and execute it using the input fields.

I have not been able to overwrite the executable file yet, but i can already edit the picture at this moment.

It is necessary to check in the incoming parameters that this is a number, Filter double or more spaces (I'm bad at Python, if I could write code in one line I could get around these restrictions), forbid special characters like (:)

**Comment by HaSHsss** [comment]
I succeeded because I know the names of the variables

**Comment by florianfesti** [comment]
Can you just send the reproducer to my commiter's email?

**Comment by HaSHsss** [comment]
I can't send private messages here
 and I don't know your email

**Comment by HaSHsss** [comment]
Just need to add  strip("/\_=+:)(")
or 
Something more powerful in regexp

**Comment by HaSHsss** [comment]
```
input =  """
				<input name="%s" maxlength="7" type="number" value="%s">
```
in `boxesserver  `as minimal step

**Comment by HaSHsss** [comment]
Oh 
input edge_types have text as valeu in 
https://festi.info/boxes.py/UnevenHeightBox

**Comment by florianfesti** [comment]
Today has been a long day. Can you just send the URL(s) to florian at festi.info , please?

**Comment by florianfesti** [comment]
455f5ae69a20c14d6da49b82baaa4c2859baed63 should at least protect against overly large numbers.

**Comment by florianfesti** [comment]
> Just need to add strip("/_=+:)(") or Something more powerful in regexp

Well, first these should actually be treated properly by quoting/unquoting them. I could not quite see where exactly they slip through the cracks by looking at the code. Also these characters are actually used in the `sx`, `sy`, `sh` parameters and in the layout descriptions of `TrayLayout` and the new `GridfinityTrayLayout`. So filtering them is not an option.


> ```
> input =  """
> 				<input name="%s" maxlength="7" type="number" value="%s">
> ```

Well, `type=number` is for integers while most inputs are floats. And we make use of that at some very important places like `thickness` and `burn`. So going to ints is not an option.

**Comment by florianfesti** [comment]
I am really not seeing how any of these special chars should be able to make it through argparse. Without a reproducer this is not going anywhere. Closing.
