### ISSUE TITLE
/bin/sh:1:boxes: not found

### ISSUE THREAD

**Issue by alexmlucas** [florianfesti/boxes#538]
Still an issue with latest revision as described in bug #537

**Comment by florianfesti** [comment]
Hmm, this looks like either `/usr/bin/env` or `python3` is not found. Can you check for both of those, please? I don't have a Debian installation at hand but I have a hard time believing they are not available. May be you don't have python3 installed?

**Comment by alexmlucas** [comment]
So i've looked and /usr/bin/env exists. Also Python 3.9.1 is installed.

**Comment by florianfesti** [comment]
Yeah, but is there a python3 binary in the path? If not, may be there is some python3 meta package containing a link. Or you need to adjust the first line of `boxes_proxy.py`

**Comment by florianfesti** [comment]
Anyway, this doesn't really look like an issue with boxes.py. Closing for now. Feel free to re-open if there are more issues.
