### ISSUE TITLE
TrayType Sides Too Long

### ISSUE THREAD

**Issue by scottdidit** [florianfesti/boxes#557]
**Description**
I create a tray type with 3 internal sections; 2 side-by-side on one end, then 1 section taking the rest of the box.  The sides, as well as the dividers are too long.  In my case, about 1.2mm too long.

**To Reproduce**
I don't have an URL, but I attached the settings I used (.pdf file).  I also attached the cut file (.svg) which contains notes pointing out the problem.

**Expected behavior**
Sides and dividers should be the correct length for the bottom.

**Screenshots or Drawings**
-none-

**Additional context**
[SampleBox02.pdf](https://github.com/florianfesti/boxes/files/11379114/SampleBox02.pdf)
![SampleBox02](https://user-images.githubusercontent.com/129767786/235827887-d88e90a0-e43b-4006-8856-2c7df0d88ff9.svg)

**Comment by florianfesti** [comment]
Yeah, turns out the base plate doesn't take the `extra_length` in the `FingerJoint Settings` into account. I wonder where else the code still assumes that the finger joints are exactly one thickness deep. Luckily the default corner does take the actual value into account. This is why the walls are bigger (as they should be). Anyway, should be reasonably easy to fix for the `TrayLayout` at least.

**Comment by scottdidit** [comment]
Thank you for responding, sorry my response back was a little slow.

How will I know when the fix has been deployed to the on-line generator page?

-=|Scott|=-

**Comment by florianfesti** [comment]
I will update this issue as soon as there are news.

I actually already started working on this, but the code for the base plate is a bit intricate and needs new parts to handle the corners. There's currently a lot of other stuff going on, so it may take a while longer.

**Comment by florianfesti** [comment]
Change just got added to the server. Please test and re-open this ticket if there are still issues.

**Comment by scottdidit** [comment]
Thank you so much.

-=|Scott|=-
