### ISSUE TITLE
Paper box error 

### ISSUE THREAD

**Issue by gyan007** [florianfesti/boxes#560]
An error occurred!
__call__() missing 1 required positional argument: 'y' 

This error shows up when trying to generate a Paper Box. Could any one look into this. Thank you

**Comment by florianfesti** [comment]
Fixed with 7459e133b25b9ae6246eda1fc3a66a5e13fafdf2

Turns out the new lid object added in 70162bdfb2046c683a083273eeec4fa7671105c6 did overwrite/shadow the method.
