### ISSUE TITLE
Request : Dice Tower

### ISSUE THREAD

**Issue by noscollections** [florianfesti/boxes#563]
To complete Dice objets, a dice tower will be great.

A simple tower like this one in the design : https://www.thingiverse.com/thing:2001685

On parameter, we could have :
The height of the tower
Section of the tower,
number of intermediat inside section with angle
size of the arrival zone of the dice.

I can make a draw if you think this a good idea

**Comment by tljuniper** [comment]
With #704 merged, can we close this issue or is there anything left to do?

**Comment by florianfesti** [comment]
Sure!. I forgot about that. Thanks for reminding me!
