### ISSUE TITLE
Inkscape Plugins disabled

### ISSUE THREAD

**Issue by rebeltaz** [florianfesti/boxes#574]
I installed the inkscape plugins using the manual method under Ubuntu 22.04 in inkscape 1.1. The plugins shows up under the extension menu, but every one is greyed out / disabled. What am  I doing wrong? 

EDIT: I managed to get the boxes2inkscape script to work (by changing "#!/usr/bin/env python3" to '#!/usr/bin/python3' and then saving it with unix encoding instead of windows) but I am still getting disabled / greyed out extensions.

I ran inkscape from the command line and it looks like a lot of things are missing! I installed the Requirements from the Installation page (the only one I was actually missing was affine).

**Comment by rebeltaz** [comment]
Further research has led me to believe that this extension is not compatible with inkscape v1.0

https://inkscape.gitlab.io/extensions/documentation/authors/update1.0.html

...
Remove dependency listings

Remove the dependency listings for the following modules:

    bezmisc.py

    coloreffect.py

    cspsubdiv.py

    cubicsuperpath.py

    ffgeom.py

    inkex.py (removal not strictly required)

    pathmodifier.py

    simplepath.py

    simplestyle.py

    simpletransform.py

    more?
...

as these are the same files being complained about.

**Comment by rebeltaz** [comment]
if anyone has this same trouble, you can run the following commands from the 'boxes-master/' directory

```
sed -i 's/env python3/python3/' scripts/*
setup.py
scripts/boxes2inkscape
mkdir ~/.config/inkscape/extensions/images 
cp static/samples/* ~/.config/inkscape/extensions/images
cd ~/.config/inkscape/extensions/
sed -i "s/<image>\./<image>images/" boxes.py.*.inx 
```

**Comment by abergmeier** [comment]
Isn't the problem with `python3` rather the Windows users, that commit CRLF?

**Comment by Deltaplc** [comment]
Good morning
Excuse my ignorance, but I haven't yet understood the procedure to create all the files necessary to use this beautiful application on inkscape!!
How do you create the boxes.exe file? And all the inx files?
Can you help me?
Can you give me a step by step guide?
I can't really understand from the instructions on the site!!!
Thank you

**Comment by florianfesti** [comment]
You might want to try MightyScape a selection of pre-build Inkscape extensions including Boxes.py:  https://gitea.fablabchemnitz.de/FabLab_Chemnitz/mightyscape-1.2-zipmirror
