### ISSUE TITLE
GridfinityTrayLayout: add horizontal 'shelf' feature for making cutouts for specific items

### ISSUE THREAD

**Issue by ccrome** [florianfesti/boxes#588]
I want the ability to automatically create horizontal, full coverage shelves in the gridfinity layout.  This will let me easily make cutouts for screwdrives, and other custom items

**Describe the solution you'd like**
Add another 'floor', and floor cutouts at specified heights.  Valid only when countx==county==1

Please assign this to me. I will update.

**Comment by ccrome** [comment]
What's the easiest way to proceed with adding a 'shelf' in these 1x1 gridfinity boxes.  Basically what I think I'm looking for is this:
![image](https://github.com/florianfesti/boxes/assets/286973/1fefe2a6-e49c-4447-8225-fb4f1f25742b)

**Comment by florianfesti** [comment]
It's probably easier to take the DrillBox and turn that into a GridFinityDrillBox generator. The issue with the TrayLayout is that there are multiple sections and you can only anker horizontal wall with finger joint from one side.

**Comment by ccrome** [comment]
ooh, this is great! just cut myself one.   images incoming.
