### ISSUE TITLE
Box idea

### ISSUE THREAD

**Issue by Mekol** [florianfesti/boxes#60]
Hey, i have got a box idea, but i dont know how to script that (also i have windows and this doesnt works for me).
The main idea is to make open-box with different heights of front and back walls.
I tried to make simple sketch for this  ;)
![opbox](https://user-images.githubusercontent.com/28317221/37434800-3038c386-27e1-11e8-983e-e4674ece3a42.png)

**Comment by ffesti** [comment]
Yeah, this probably deserves a generator of it's own. For now you can use a single "TrafficLight" turned upwards. Just delete the front and the FingerJointHoles for it.

**Comment by florianfesti** [comment]
Try https://www.festi.info/boxes.py/UnevenHeightBox

**Comment by Mekol** [comment]
Looks great, thanks for adding feature. I will test it. 😉

15 mar 2018 7:11 PM "Florian Festi" <notifications@github.com> napisał(a):

**Comment by florianfesti** [comment]
Added param for bottom_edge

**Comment by florianfesti** [comment]
Ok, tested and looks good. Two with low, high, low, high can be stacked on top of each other.

**Comment by florianfesti** [comment]
Added optional lid.

**Comment by Mekol** [comment]
something is wrong using default settings(with lid)
​

2018-03-17 18:43 GMT+01:00 Florian Festi <notifications@github.com>:

**Comment by Mekol** [comment]
![bxes](https://user-images.githubusercontent.com/28317221/37558493-55c7d958-2a15-11e8-8fc8-534d759f22bc.png)
