### ISSUE TITLE
Add `pre-commit` for code style

### ISSUE THREAD

**Issue by Rotzbua** [florianfesti/boxes#600]
## Suggestion

`pre-commit` is a tool that formats and checks the changed code before each commit.

## Pro

One advantage is that it automatically sets up its own environment for each tool, so the user does not have to install and configure each tool.

Many predefined tools are available: https://pre-commit.com/hooks.html

## Con

Must be actively installed by the user.

GH Action does not make annotations.

## Reference

https://pre-commit.com/

**Comment by florianfesti** [comment]
Completed with #601
