### ISSUE TITLE
Font errors

### ISSUE THREAD

**Issue by kakalot** [florianfesti/boxes#61]
![image](https://user-images.githubusercontent.com/4798571/37944224-02e2bbee-31a5-11e8-974b-5c335ec11ae1.png)

Hello, as you see it generated with font errors on any templates. Can you fix it? Thank you!

**Comment by ffesti** [comment]
Yes, this is a known problem. Unfortunately I have not been able to figure out what's the problem. It looks like something on the server running the web interface broke. I already tried setting the font explicitly but nothing helped.
You can run boxes.py locally on a more modern Linux system and the fonts are rendered just fine.
If you do not have a Linux computer at hand I can generate the file for you if you give me the desired thickness and burn.

**Comment by kakalot** [comment]
Hi, thank you for surporting. No problem, i will fix in svg files for myself

**Comment by florianfesti** [comment]
Just for the record. The server is running CentOS Linux release 7.5.1804 (Core) 
with httpd-2.4.6-80.el7.centos.1.x86_64, mod_wsgi-3.4-12.el7_0.x86_64, python-2.7.5-69.el7_5.x86_64 and cairo-1.14.8-2.el7.x86_64. The error happens with both pycairo and cairocffi *sigh*

**Comment by florianfesti** [comment]
Ok, I've been playing around with moving the instance into a more modern docker container. This fixes the issue. Still need to do a bit of engineering to set this up properly. Still closing this ticket now.
