### ISSUE TITLE
Add date and identifier arguments to burn test generator

### ISSUE THREAD

**Issue by sethfischer** [florianfesti/boxes#621]
I've created a [custom burn test generator](https://github.com/sethfischer/boxes-builds/blob/a627aa0aa13551312615170d80b02ac74200a8c5/generators/burntestcustom.py) which adds the options to etch the date and/or an identifier onto the parts. The additional options are:

* `--date`: add current date etching to each piece
* `--id`: add identifier etching to each piece

Example command:

```
boxes BurnTestCustom --date=1 --id="my identifier"
```
Example output:

![custom-burn-test-with-date-id](https://github.com/florianfesti/boxes/assets/2492233/967dbf05-2ab0-4803-b99f-817a52d078e5)

If users would find this feature useful (or variations on this feature) I'd be happy to submit a pull request.

**Comment by florianfesti** [comment]
This looks useful. Especially for people with multiple laser cutters but also for comparing different settings. Merging these changes in the upstream generator is very welcome.
