### ISSUE TITLE
ElectronicsBox - Lid thickness option

### ISSUE THREAD

**Issue by Dumnac** [florianfesti/boxes#629]
Hi, 

Thanks for this amazing box generator.

I made an electronics box with a custom lid who have a different thickness materiel than the box itself. 
To fit with the box edge I had to modify the DXF file to raise the triangles holding holes :

![IMG_20240214_155809](https://github.com/florianfesti/boxes/assets/34985946/a95ffe3e-df99-4754-b2bb-b9c3d242dfe4)

It would be interesting to add an option to choose the lid thickness .

**Comment by florianfesti** [comment]
Well, there is a limited amount of options that can be added while there is an unlimited amount of options people can think of. You can also just let the lid be a little bit lower and have it better protected from scratches. I understand that such option would have been handy for you and adding it is not to difficult. But may be having the UI a bit more siple is just the better option.
