### ISSUE TITLE
Flexbox4 latchsize incorrect dimension

### ISSUE THREAD

**Issue by Ricu64** [florianfesti/boxes#649]
**Describe the bug**
the latch edge is not correctly in the box border 
**To Reproduce**

**Expected behavior**

**Screenshots or Drawings**
![FlexBox4](https://github.com/florianfesti/boxes/assets/164808740/8719addf-f6ae-42a4-997c-933def7f4aab)

**Additional context**
great work! tanks, best regards. enrico

**Comment by florianfesti** [comment]
I am sorry. This code is so old it is out of warranty...
