### ISSUE TITLE
Shelf for laptop and phone charger pad

### ISSUE THREAD

**Issue by SnowBeaver** [florianfesti/boxes#656]
**Describe the solution you'd like**
It is an extension of the Display Shelf with one shelf. Few modifications to the shelf are required. First is to move the back panel to the front. The shelf should be raised to leave room for the botton charger and finally,  a botton should be added. See pictures.  We should also add holes on either side of the botton shelf for usb cables.

Thanks, Michel. 

** Pictures of something similar **
Here are pictures of an edited shelf. 
![PXL_20240401_181612058](https://github.com/florianfesti/boxes/assets/14792954/46125f89-3519-43cd-b76e-935a99995daa)
![PXL_20240401_181559519](https://github.com/florianfesti/boxes/assets/14792954/c4e3d0ba-385f-4a2b-a59d-e2c0fef43494)

**Comment by SnowBeaver** [comment]
Updated description.

**Comment by florianfesti** [comment]
Not quite sure why you don't just use a normal DisplayShelf without a back wall. That should be strong enough and with setting `front_wall_height` large enough Things should not fall through. Also you get holes at the back for free.

**Comment by SnowBeaver** [comment]
I need the back panel to fix the box to a wall.  That is why I need holes
on the side panels.

Thanks for your reply.

**Comment by SnowBeaver** [comment]
Here is the shelf fixed to a small cabinet. Modification that could be added are holes for the usb cables,  support for holding the usb power supply. Thanks
![PXL_20240404_150022690](https://github.com/florianfesti/boxes/assets/14792954/97c5dbf5-3394-45f0-bfb7-08cfbf77fc22)
![PXL_20240404_150321303](https://github.com/florianfesti/boxes/assets/14792954/164af3ce-1cee-496b-9542-de3082efaa27)
![PXL_20240404_150416278](https://github.com/florianfesti/boxes/assets/14792954/c42d9cc0-54f7-4dd0-981a-a43535f5fe26)

**Comment by florianfesti** [comment]
OK, you can now have walls at the bottom the front or the back. Holes for cables need to be added by yourself e.g. using Inkscape.

Pleas have a look if everything fits together.

**Comment by SnowBeaver** [comment]
Thanks Florian.

I looked at https://www.festi.info/boxes.py/DisplayShelf?language=en but
the options are the same. I suppose to have a look at your changes I must
run the code using python, but I do not know how to do it, at least I did
not find it.

Michel

**Comment by florianfesti** [comment]
Ops, forgot to update the web instance...

Should be there now.

**Comment by SnowBeaver** [comment]
I tried it and I have a  few comments:

The bottom need more height with the shelf. it should be variable to adjust to every user needs. 
![image](https://github.com/florianfesti/boxes/assets/14792954/faf4d6c6-37fe-4015-9e0a-f4b9b17eb4e1)

With the following settings, the shelf go outside the box and should be clipped

![image](https://github.com/florianfesti/boxes/assets/14792954/b29415fb-fd32-4ea6-9e2c-c859bdd0ef52)

![image](https://github.com/florianfesti/boxes/assets/14792954/f4db9975-96bb-4215-bbc1-4265c6291f4b)

**Comment by florianfesti** [comment]
9972d329b2d15c91a1e6d6f594fcc4894b9e7f34 and 769236b5df3de9c009b74eda59a57c62e617ed96 fixes placement issues of the shelves and issues an error to the user if the shelves won't fit in the height.
