### ISSUE TITLE
Broken box generators without arguments

### ISSUE THREAD

**Issue by Rotzbua** [florianfesti/boxes#664]
**Describe the bug**
Box generator throws error without arguments.

**To Reproduce**

- WallConsole
- HolePattern
- FillTest
- TrayLayoutFile
- TrayLayout
- GridfinityTrayLayout

**Expected behavior**
Work without arguments with default values or show help text.

**Comment by florianfesti** [comment]
I'll look into that.

**Comment by florianfesti** [comment]
Ok, the one above should be fixed. The Layout stuff now complains about the missing input file.
