### ISSUE TITLE
Failing test: Shadowbox sample

### ISSUE THREAD

**Issue by gcollic** [florianfesti/boxes#674]
**Describe the bug**

When running the commands from the contributing guidelines, a test is failing.

**To Reproduce**

When running `pre-commit run --all-files` or directly `pytest`, the test `TestSVG.test_generator[Shadowbox]` is failing (`SVG files are not equal. If change is intended, please update example files.`).

Indeed, after executing `python .\scripts\boxes --examples`, `git status` shows `modified: examples/Shadowbox.svg`.

I suppose updating the example is needed, but not knowing this box I'm not sure if the difference is right or wrong.

**Screenshots or Drawings**

![image](https://github.com/florianfesti/boxes/assets/763200/22acb035-9fec-424b-9f9e-c0662c21f004)

**Additional context**

The added 4 shapes are surely from #672, but I'm not sure about the other 2 disappearing.

**Comment by florianfesti** [comment]
I somehow count 14 pieces for both sides...

Looks light they just got a bit thinner.

**Comment by florianfesti** [comment]
d2422e43256bcd22c2b49e80e0f54becfc2096bb fixes this en passant.

**Comment by gcollic** [comment]
Thanks!
And sorry for the misdirection, the view was scaled differently in inkscape, I was mistaken
