### ISSUE TITLE
ontop lid incompatible with default TypeTray separators

### ISSUE THREAD

**Issue by jasondunsmore** [florianfesti/boxes#681]
When an ontop lid is used with a TypeTray that has separators, the alignment pieces run into the separators.  As a possible fix, the inner height of inner walls should be made lower when ontop lid is used. Alternatively, there could be a small cutout in the tops of the separators to allow clearance for the alignment pieces.

**To Reproduce**

    boxes TypeTray --sx=100/2 --sy=100/2 --h=100 --top_edge=e --Lid_style=ontop --gripwidth=0

**Expected behavior**

The lid should fit on the box.

**Comment by jasondunsmore** [comment]
![image](https://github.com/florianfesti/boxes/assets/53437/86f27f34-12e8-47ed-a46c-910fe3010b31)

**Comment by florianfesti** [comment]
Yes, easily reproduced. Still meditating on what's the easiest way so solve this.

**Comment by florianfesti** [comment]
OK, reduced the lips to small pieces in the corners. There may still be issues for very small (<= 4 * thickness) compartments. But I am ignoring this for now.
