### ISSUE TITLE
RackBox generator is not positioning mounting holes in correct place.

### ISSUE THREAD

**Issue by unsigneduk** [florianfesti/boxes#683]
**Describe the bug**
Holes generated for the mounting plate are not generating in the correct place

**To Reproduce**
https://boxes.hackerspace-bamberg.de/RackBox?language=en, I use Firefox and the latest version of lightburn. Seems to only be reproducable when using material thicker than 3-4mm. Using 6mm material the mounting holes moved outside the workpiece. 

**Expected behavior**
Generally I leave most of the settings for all the generators at the defaults in this case it is 7mm from the edge which seems to be working for all other hole positions just not two on the mounting plate.

**Screenshots or Drawings**
If the bug can't be reproduced easily, add screenshots or attach a drawing to help explain your problem.

**Additional context**

**Comment by florianfesti** [comment]
Yeah. The issue is that the whole is located from the top of the whole box and not from the top of the front piece which is one material thickness lower. So I guess the solution is to make the front piece higher - at least on the sides.

**Comment by florianfesti** [comment]
OK, there is actually a lot more wrong with the height of the box. Also the top holes should probably not be relative to the top of the box but in the grid of the mounting rails.

**Comment by unsigneduk** [comment]
It looks to me with a clearer head this morning that the box is being produced acuratly just not the two holes mentioned. However as a temporary solution within Lightburn you can "ungroup" the offending part move the mounting hole a few mm and re-group. Solved at least until it is fixed.

**Comment by florianfesti** [comment]
Ok, turns out this box is not really meant for a regular Rack with imperial hole spacing. So I now have the holes in the corners as the parameters suggest.

**Comment by unsigneduk** [comment]
Thanks Florian thats brilliant. Really handy script among others too.
