### ISSUE TITLE
FlexTest2 export to Lightburn not functioning correctly

### ISSUE THREAD

**Issue by ClaneSharke** [florianfesti/boxes#695]
When exporting the flex test 2 to Lightburn file it generates additional lines

https://boxes.hackerspace-bamberg.de/FlexTest2?x=100.0&y=100.0&fw=1&thickness=3.2&format=svg&tabs=0.0&qr_code=0&debug=0&labels=0&reference=0&inner_corners=loop&burn=0.08&language=en&render=1

The output should be the same as exporting to SVG without the additional lines.

![image](https://github.com/user-attachments/assets/ee213a72-d550-4bbf-89f0-c37f5aa9e4f9)

Thanks for your support

**Comment by florianfesti** [comment]
Ok, I think I found it.
