### ISSUE TITLE
Scaling off

### ISSUE THREAD

**Issue by MAKOMO** [florianfesti/boxes#7]
Since commit 0ba0c19 "Detect size of drawing and set svg viewport accordingly" (some of?) my cuts are longer (in x-direction) than designed.

My process is: boxes -> VisiCut -> Zing-Laser

On verifying my designs in Inkscape all measurements are as expected, but in VisiCut the x-size of objects tend to be somewhat larger (scaled up).

Here an example of a very simple object (I can provide the source on demand) looks like this in Inkscape

<img width="318" alt="screen shot 2016-06-22 at 09 05 07" src="https://cloud.githubusercontent.com/assets/13909011/16257406/bc42ce6e-3858-11e6-9d56-e88897cbf0a0.png">

which looks like this in the VisiCut preview (and cuts on the Zing in those extended dimensions)

<img width="371" alt="screen shot 2016-06-22 at 09 05 45" src="https://cloud.githubusercontent.com/assets/13909011/16257491/31eb0b54-3859-11e6-891b-537802d951de.png">

If I go back to the version of boxes where the canvas dimensions had to be set manually, I get the same result in Inkscape, but the correct size in the VisiCut preview (as well in the Zing output):

<img width="397" alt="screen shot 2016-06-22 at 09 05 29" src="https://cloud.githubusercontent.com/assets/13909011/16257495/3b346c64-3859-11e6-9267-e7ad082d4033.png">

Only the x-dimension seems to suffer from this scaling issue. I now stepped back to the version before that commit and the x-scaling issue seem to be gone.

I have to note that this issue might be caused by VisiCut, which is know to have issues in interpreting the design dpi of SVGs and tries to recognize the creator of designs to adjust its interpretation.

https://github.com/t-oster/VisiCut/issues/174
https://github.com/t-oster/VisiCut/issues/347

Not having any idea of the SVG format, I quickly looked at the generated file headers and see for the trunk version

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="  80mm" height="  60mm" viewBox="0 940  70  60" version="1.1">
`

and for the boxes version with the manual viewport setting

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100mm" height="64mm" viewBox="0 0 100 64" version="1.1">`

If I adjust the version generated by boxes trunk to (not knowing what I am doing) to

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="80mm" height="60mm" viewBox="0 940  80  60" version="1.1">`

VisiCut seems to interpret the x-scale correctly again.

Thanks for sharing your wonderful work!

**Comment by florianfesti** [comment]
Thanks for spotting this. The problem is caused by the viewport detection code not getting minx as 0 while the code updating the svg file leaving the start in x direction unchanged at 0 (due to the lack of space in the file). This causes the size of the drawing and the viewport not match up and though getting the drawing rescaled in x direction.
