### ISSUE TITLE
Documentation of settings for the Wall Mounted edges, especially the French Cleat

### ISSUE THREAD

**Issue by jaypeeds** [florianfesti/boxes#700]
The comments in the code don't allow to guess how the "hook" or "stud" values for the bottom setting affect the design.

An example of simple box with French cleats wall mounting would be nice.

Thank you for your contribution so far.

**Comment by florianfesti** [comment]
Unfortunately I don't have a French Cleat wall. If you have cut a few boxes please upload pictures to #628.
