### ISSUE TITLE
Upgrading Inkscape Extension? 

### ISSUE THREAD

**Issue by rebeltaz** [florianfesti/boxes#702]
I installed this as an inkscape extension last year, after quite a bit of modification to the setup scripts. I've noticed that there has been some work done and some new additions. To install the new version, do I need to remove the old version? install this over top of the old version? or could I just extract the boxes/x.py files (and the associated images) and call it a day?

**Comment by florianfesti** [comment]
Technically removing the old files is mandatory. But AFAIK we didn't really remove any files so they should all be overwritten. If in doubt delete all `*.pyc` files as those do get generated again.
