### ISSUE TITLE
Thoughts on cardboard box generator.

### ISSUE THREAD

**Issue by ccrome** [florianfesti/boxes#703]
Have you given thought to a cardboard box generator?  Something that gives cut and scribe lines for folds.

**Is your feature request related to a problem? Please describe.**
My problem -- I just need some quick and dirty cardboard boxes of a specific size.

**Describe the solution you'd like**
* Box generator with different top and bottom closures. 
* There are so many options.  Not sure where to start, but I guess just a simple box with taped bottom and a folding tuck-in top.

** Pictures of something similar **
https://www.template.net/design-templates/box-templates/sample-cardboard-box/
![image](https://github.com/user-attachments/assets/c51f76ed-9a38-429b-b262-a1d35eda16e5)

**Comment by florianfesti** [comment]
There is the PaperBox generator. Any changes you need there?

**Comment by ccrome** [comment]
🤦‍♂️ I hadn’t seen that one!  I was searching for cardboard. That looks perfect!  Thanks!
