### ISSUE TITLE
Sliding Drawer rounded outer corners

### ISSUE THREAD

**Issue by pellematrose** [florianfesti/boxes#706]
The sliding drawer outputs now files with roundet outer corners instead of simply rectangular ones.
I could not find any parameters to change. Some weeks ago I could not see this behaviour.

![slidingdrawer_rounded](https://github.com/user-attachments/assets/dad1a9a6-4c81-4545-9b70-ae7fdb4d5d7a)
![slidingdrawer_rectangular](https://github.com/user-attachments/assets/247c4f11-fdee-486b-b694-c55f19aa9bc7)

Is it a feature or a bug?

Thank you!

**Comment by florianfesti** [comment]
See https://florianfesti.github.io/boxes/html/api_burn.html and https://florianfesti.github.io/boxes/html/faq.html#why-are-there-tiny-weird-loops-in-the-corners

**Comment by florianfesti** [comment]
You probably set the burn correction to something else than zero.

**Comment by pellematrose** [comment]
> You probably set the burn correction to something else than zero.

You are right. I set it to 0.6. I wanted 0.06.
But thats actually a nice feature if you want rounded corners. ;)
