### ISSUE TITLE
Tray Lay Out Process Discription

### ISSUE THREAD

**Issue by KellisR** [florianfesti/boxes#727]
Edit: I figured out the problem I was having, but only because I had read through some of the comments on screen rendering and pulled the layout text box open. 

**Is your feature request related to a problem? Please describe.**
I can't understand the instructions in part 2

**Describe the solution you'd like**
Replace the start code with the code to create the tray in the example. It will provide a clear example of how to remove walls. 
"You can replace the hyphens and vertical bars representing the walls with a space character to remove the walls."
looks like. This example is wrong but I can't figure out why. If the code used to create the tray in the picture was used, a graphic example wouldn't be required.  

Edit: Add text to step 2 stating the layout box may need to be enlarged until all dimensions render on the right. I didn't need to remove any hyphens. If not required suggest reference to hyphens be removed.
** Pictures of something similar **

![image](https://github.com/user-attachments/assets/48cbc988-d4c0-44df-a95b-b73e8cefdfae)

Edit: After enlarging the layout text box:

![image](https://github.com/user-attachments/assets/c5ce65f5-badd-4128-8320-55c8d0800e53)

Thank you everyone who contributes to Boxes.py

**Comment by florianfesti** [comment]
Weird, for it works fine with both Chromium and Firefox even with the lines broken. But in your first picture the | at the end does not line up.

But the description surely can be improved.
