### ISSUE TITLE
`boxes` no longer installable in a virtual environment

### ISSUE THREAD

**Issue by sethfischer** [florianfesti/boxes#728]
`boxes` is no longer installable as a module in a virtual environment.

## Description

5fc17de321f6a1491e0a9b1ce7535c3e73e9b062 can be installed as a module in a virtual environment:

```console
$ pip install git+https://github.com/florianfesti/boxes.git@5fc17de321f6a1491e0a9b1ce7535c3e73e9b062
$ boxes --list
Available generators:
⋮
```

The tip of master 44df0ae can no longer be installed in the same manner.

### 5fc17de with Python 3.9 (working)

```console
$ virtualenv --python 3.9 venv
$ . venv/bin/activate
$ python --version
Python 3.9.20
$ pip install git+https://github.com/florianfesti/boxes.git@5fc17de321f6a1491e0a9b1ce7535c3e73e9b062
$ boxes --list
Available generators:

Boxes

 *  ABox  -  A simple Box
⋮
```

### Master 44df0ae with python 3.11 (not working)

```console
$ virtualenv --python 3.11 venv
$ . venv/bin/activate
$ python -m ensurepip --upgrade
$ python --version
Python 3.11.10
$ pip install git+https://github.com/florianfesti/boxes.git@master
$ boxes --list

Command 'boxes' not found, but can be installed with:

sudo apt install boxes
```

### Master 44df0ae with python 3.9 (not working)

``` console
$ virtualenv --python 3.9 venv
$ . venv/bin/activate
$ python --version
Python 3.9.20
$ pip install git+https://github.com/florianfesti/boxes.git@master
$ boxes --list
Traceback (most recent call last):
  File "/home/seth/tmp/boxes-master/venv/bin/boxes", line 5, in <module>
    from scripts.boxes import main
ModuleNotFoundError: No module named 'scripts'
```

## Expected behaviour

It would be fantastic if boxes could be installed into a virtual environment as 5fc17de was.

## Additional context

See https://github.com/sethfischer/boxes-builds for one example of why installing boxes into a virtual environment is useful.

**Comment by florianfesti** [comment]
Easily reproduced. This is obviously caused by the move to pyproject.toml in 69c26626e3502de2a46bc6d6ff1e448d4170bc30.

I do have a patch fixing this already but it needs a bit more polishing - especially to make sure it won't break the web instance.
