### ISSUE TITLE
_swtemplate.py is not valid

### ISSUE THREAD

**Issue by AlexCPU** [florianfesti/boxes#730]
**Describe the bug**
There's two templates in the generators folder, I presume the swtemplate is for wall mounted designs, but it seems to be out of date.

**To Reproduce**

- Copy _swtemplate.py to swtest.py
- Change classname to SWTest
- Find on the HTML dashboard
- error in console says:
`AttributeError: module 'boxes.edges' has no attribute 'SlatWallSettings'`

**Expected behavior**
Template works

**Comment by florianfesti** [comment]
This is just a quick untested fix based on the code found in wallwrenchholder.py. Feel free to reopen if it does still not work properly.

**Comment by AlexCPU** [comment]
Thanks, that's pointed me enough in the right direction!

Couple of changes to actually make it work (I don't think I have the permission to reopen):

`super().__init__(self)`
goes to
`super().__init__()`

Remove the FingerJointSettings line, as that gets automatically added.

**Comment by florianfesti** [comment]
Fixed. Now the `ignore-errors` is no longer needed.
