### ISSUE TITLE
undefined and unused variables in flexbox4.py

### ISSUE THREAD

**Issue by MAKOMO** [florianfesti/boxes#8]
Minor: 

x and y are not defined in flexbox4:render() and self.c4 is never used.

```
    def render(self):
        self.radius = self.radius or min(x, y)/2.0
        self.c4 = c4 = math.pi * self.radius * 0.5
```

**Comment by florianfesti** [comment]
self.c4 is used in .surrounding Wall(). Fixed the x and y var to self.x, self.y.
