### ISSUE TITLE
Burn forming overlapping Paths

### ISSUE THREAD

**Issue by zaidpirwani** [florianfesti/boxes#95]
Hi, this is the same issue as described in https://github.com/florianfesti/boxes/issues/42 I am adding an image, I agree that the kerf parameter is needed and I have been using your generator for quite some time now, However, if I take the exported SVG or DXF and load it up in SolidWorks for making 3D renders and adding in more details, it breaks - SolidWorks and other CAD software dont like the overlapping paths.

Can we have KERF while generating non-overlapping parts ? for now, I will try without the kerf parameter and see how it works for my LASER.

![image](https://user-images.githubusercontent.com/1651976/47337549-de2d5800-d6ad-11e8-8e93-ee68ac63328b.png)
I usually keep the burn at 0.075 to 0.1

Anyways, THANKS for an awesome generator.

**Comment by florianfesti** [comment]
I am kinda hesitant to try to implement a different way of doing the burn correction. Even if it would be done one would want dog bones which are also likely to lead to overlapping tool paths. 

There is actually code to do kerf for a set of points in boxes.vectors. But using something like it throughout Boxes.py would be a non trivial change.

**Comment by zaidpirwani** [comment]
for now, we are using BURN=0, it is working for us, though the pieces are a bit loose when fit together, we are trying to figure this out and somehow implement it in our process while designing items for LASER Cutting in SolidWorks.

**Comment by florianfesti** [comment]
Closing this here. Please still post here or on Hackaday.io if you find a solution that works for you. This may be interesting for other users, too.
