### ISSUE TITLE
PaintStorage - space between shelves

### ISSUE THREAD

**Issue by Blancanegra** [florianfesti/boxes#99]
The space between shelves allows to catch the paint cans, but would be great to make it optional if you don't need it, reducing vertical storage space.

![20181112161404_img_4913](https://user-images.githubusercontent.com/32768345/48472543-d5d0c480-e7f6-11e8-9c8a-c14a68ea5c1e.JPG)
![space between shelves](https://user-images.githubusercontent.com/32768345/48472745-3829c500-e7f7-11e8-9671-9c9e216bf61b.jpg)

**Comment by florianfesti** [comment]
Ok, fixed in the repo. Haven't updated the web instance yet.

Also fixed the height of the small pieces at the bottom, so it is standing on the feet.

**Comment by Blancanegra** [comment]
I was manually editing the height of those pieces for my paint stands, both fixes are great!

Now that I have a few paint stands full of paint bottles I think it would be necessary to add a grip hole in the side walls to catch and move them safely.

**Comment by florianfesti** [comment]
Added a grip hole and updated the web instance
